// @generated by tools/ecdlp_codegen.py
// generator-version: ecdlp-codegen/v1
// generator-sha256: 9f2e055ad2441049ef63a01ac34341c7fcc8880323d3734b573036cb5d6d8471
// profile-sha256: afc3be6a118b3dead47539821d6e0f4eb7186479b0ffdcead2c95eecc8e91790
// artifact: binary_gcd_in_place_inactive.rs
// formal-input: formal/lean/EccFormal/PointAddAlgorithm.lean sha256=e83ac9d653eea9750badc997f47623f38b7713962a792c5a3cca052df6096184 authority=kernel-proved theorems=EccFormal.PointAddAlgorithm.parent_register_composition_refines_affine
// formal-input: formal/lean/EccFormal/BinaryGcdConvergence.lean sha256=628c7ba200df167c9707dfedcf381b9a344bd1b550f4157404dbf46ccda90712 authority=kernel-proved theorems=EccFormal.BinaryGcdConvergence.secp256k1_complete_fixed_511
// formal-input: formal/lean/EccFormal/BinaryGcdGarbageReplay.lean sha256=39b046f88cc76dc84a776c71a66a28b66d11989dbce6c3bb89565e3f4b027542 authority=kernel-proved theorems=EccFormal.BinaryGcdGarbageReplay.inverse_value_walk_restores_complete_trace,EccFormal.BinaryGcdGarbageReplay.coefficient_replay_complete_coprime_orientation,EccFormal.BinaryGcdGarbageReplay.coefficient_replay_complete_coprime_inverse_orientation
// formal-input: formal/lean/EccFormal/BinaryGcdInPlaceMultiplication.lean sha256=2ff4c7e2cb450e8a8c2b1fc668f966bc7a1747a533c5fbd23d3b24b4bc2b0395 authority=kernel-proved theorems=EccFormal.BinaryGcdInPlaceMultiplication.complete_in_place_multiply_relation
// formal-input: formal/lean/EccFormal/BinaryGcdPhysicalRelease.lean sha256=ebd123fb2916831caf2f5dd9a4ae3670071e4bc12c48bf629ecbc72c5bb46668 authority=kernel-proved theorems=EccFormal.BinaryGcdPhysicalRelease.secp256k1_uniform_high_wires_clear,EccFormal.BinaryGcdPhysicalRelease.fixed_replay_peak_with_seven_scratch
// formal-input: formal/lean/EccFormal/BinaryGcdUniformLedger.lean sha256=1032c4b9fd203bd502aa577468a06a2e80200a9a64ae682a90b134eeadfa1ae4 authority=kernel-proved theorems=EccFormal.BinaryGcdUniformLedger.secp256k1_uniform_component_widths,EccFormal.BinaryGcdUniformLedger.forward_persistent_cap
// formal-input: formal/lean/EccFormal/ApproxReplayBadEvents.lean sha256=064f5d305cf9bd94e6e2a56abbf997ad70c1b46bc3c8b68c1c6b84121093a8d9 authority=kernel-proved theorems=EccFormal.ApproxReplayBadEvents.replay_exact_of_no_bad_along,EccFormal.ApproxReplayBadEvents.final_mismatch_implies_bad_visited
// formal-input: formal/lean/EccFormal/LoanAwareHybridAdder.lean sha256=7aa55ec68bea0f56987dffd5baba336ce941e64b3442b9adb9cdc5c40e851439 authority=design-provenance theorems=EccFormal.LoanAwareHybridAdder.masked_add_refines_controlled_add,EccFormal.LoanAwareHybridAdder.loaded_loan_restores_clean
// formal-input: formal/lean/EccFormal/PrefixComparator.lean sha256=0711ec8db304a58b077eb5d519d8db94d14cb309502a6318ca129c36cb0be02e authority=design-provenance theorems=EccFormal.PrefixComparator.prefix_less_exact_off_bad_event
// authority-boundary: deterministic structural generation; theorem scope remains per formal-input
// DO NOT EDIT; regenerate from the reviewed profile.
//! Generated target adapter for Schrottenloher Algorithms 2 and 3.
//!
//! Forward and explicit-inverse orientations bind the four directly generated
//! replay streams to the contest `B`/`QubitId`/`BitId` ABI. The historical
//! filename is retained solely for frozen operation-stream parity.

use super::{BitId, QubitId, B};
use crate::circuit::Op;
#[cfg(test)]
use crate::circuit::{OperationType, NO_BIT, NO_QUBIT, NO_REG};
use sha3::{Digest, Sha3_256};
use std::collections::{BTreeMap, BTreeSet};

const WIDTH: usize = 256;
const ROUNDS: usize = 2 * WIDTH - 1;
const RAW_MEASUREMENT_BITS: usize = 1788;
const TRIPLE_MEASUREMENT_BITS: usize = 5364;
const RAW_STREAM: &str = include_str!("binary_gcd_replay_raw_v1.ir");
const REVERSE_TRIPLE_STREAM: &str = include_str!("binary_gcd_replay_reverse_triple_v1.ir");
const INVERSE_RAW_STREAM: &str = include_str!("binary_gcd_inverse_replay_raw_v1.ir");
const INVERSE_TRIPLE_STREAM: &str = include_str!("binary_gcd_inverse_replay_triple_v1.ir");
const INVERSE_RAW_MEASUREMENT_BITS: usize = 1785;
const INVERSE_TRIPLE_MEASUREMENT_BITS: usize = 5355;
const EXPECTED_LIFECYCLE_FNV1A128: &str = "1df29cf46eb6c925003720c51cf87095";
const EXPECTED_INVERSE_LIFECYCLE_FNV1A128: &str = "0188246fe5b6de91677ac8c9dce256f1";

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct Wire {
    logical: usize,
    target: QubitId,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub(super) struct BoundCounts {
    pub x: usize,
    pub cx: usize,
    pub ccx: usize,
    pub swap: usize,
    pub neg: usize,
    pub z: usize,
    pub cz: usize,
    pub ccz: usize,
    pub hmr: usize,
    pub reset_z: usize,
    pub push_condition: usize,
    pub pop_condition: usize,
    pub release_r: usize,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(super) struct BindingReport {
    pub target_operations: usize,
    pub target_operation_sha3_256: String,
    pub lifecycle_operations: usize,
    pub lifecycle_fnv1a128: String,
    pub measurement_bits: usize,
    pub peak_qubits: u32,
    pub total_qubit_ids: u64,
    pub counts: BoundCounts,
}

struct Adapter<'a> {
    b: &'a mut B,
    next_logical: usize,
    free_logical: Vec<usize>,
    active: BTreeMap<usize, (QubitId, String)>,
    historical: BTreeMap<usize, QubitId>,
    measurement_bits: usize,
    lifecycle_operations: usize,
    lifecycle_fnv1a128: u128,
    counts: BoundCounts,
}

impl<'a> Adapter<'a> {
    fn new(b: &'a mut B, x: &[QubitId], y: &[QubitId]) -> Result<Self, String> {
        if x.len() != WIDTH || y.len() != WIDTH {
            return Err(format!(
                "inactive binary-GCD binding requires two {WIDTH}-qubit words"
            ));
        }
        let unique: BTreeSet<_> = x.iter().chain(y).copied().collect();
        if unique.len() != 2 * WIDTH {
            return Err("x and y target words alias".to_string());
        }
        let mut out = Self {
            b,
            next_logical: 0,
            free_logical: Vec::new(),
            active: BTreeMap::new(),
            historical: BTreeMap::new(),
            measurement_bits: 0,
            lifecycle_operations: 0,
            lifecycle_fnv1a128: 0x6c62272e07bb014262b821756295c58d,
            counts: BoundCounts::default(),
        };
        // The source lifecycle registers y before the multiplier x.
        for (bit, &target) in y.iter().enumerate() {
            out.acquire_external(target, format!("preserved-y[{bit}]"));
        }
        for (bit, &target) in x.iter().enumerate() {
            out.acquire_external(target, format!("value-v[{bit}]"));
        }
        Ok(out)
    }

    fn fingerprint(&mut self, line: String) {
        const FNV_PRIME: u128 = 0x0000000001000000000000000000013b;
        self.lifecycle_operations += 1;
        for byte in format!("{line}\n").bytes() {
            self.lifecycle_fnv1a128 ^= byte as u128;
            self.lifecycle_fnv1a128 = self.lifecycle_fnv1a128.wrapping_mul(FNV_PRIME);
        }
    }

    fn acquire_external(&mut self, target: QubitId, owner: String) -> Wire {
        let logical = self.next_logical;
        self.next_logical += 1;
        assert!(self
            .active
            .insert(logical, (target, owner.clone()))
            .is_none());
        assert!(self.historical.insert(logical, target).is_none());
        self.fingerprint(format!(
            "AcquireExternal {{ wire: {logical}, owner: {owner:?} }}"
        ));
        Wire { logical, target }
    }

    fn acquire_zero(&mut self, owner: String) -> Wire {
        let logical = self.free_logical.pop().unwrap_or_else(|| {
            let value = self.next_logical;
            self.next_logical += 1;
            value
        });
        let target = self.b.alloc_qubit();
        if let Some(&expected) = self.historical.get(&logical) {
            assert_eq!(
                target, expected,
                "target free-list order diverged at logical wire {logical}"
            );
        } else {
            self.historical.insert(logical, target);
        }
        assert!(self
            .active
            .insert(logical, (target, owner.clone()))
            .is_none());
        self.fingerprint(format!(
            "AcquireZero {{ wire: {logical}, owner: {owner:?} }}"
        ));
        Wire { logical, target }
    }

    fn acquire_specific(&mut self, wire: Wire, owner: String) {
        assert!(!self.active.contains_key(&wire.logical));
        let logical_position = self
            .free_logical
            .iter()
            .position(|&candidate| candidate == wire.logical)
            .unwrap_or_else(|| panic!("logical wire {} unavailable", wire.logical));
        self.free_logical.swap_remove(logical_position);
        let target_position = self
            .b
            .free_qubits
            .iter()
            .position(|&candidate| candidate == wire.target.0)
            .unwrap_or_else(|| panic!("target qubit {} unavailable", wire.target.0));
        self.b.free_qubits.swap_remove(target_position);
        self.b.active_qubits += 1;
        if self.b.active_qubits > self.b.peak_qubits {
            self.b.peak_qubits = self.b.active_qubits;
            self.b.peak_ops_idx = self.b.ops.len();
            self.b.peak_phase = self.b.phase;
        }
        assert!(self
            .active
            .insert(wire.logical, (wire.target, owner.clone()))
            .is_none());
        self.fingerprint(format!(
            "AcquireZero {{ wire: {}, owner: {owner:?} }}",
            wire.logical
        ));
    }

    fn release_zero(&mut self, wire: Wire) {
        let (target, owner) = self
            .active
            .remove(&wire.logical)
            .unwrap_or_else(|| panic!("release of inactive logical wire {}", wire.logical));
        assert_eq!(target, wire.target);
        self.free_logical.push(wire.logical);
        self.fingerprint(format!(
            "ReleaseZero {{ wire: {}, owner: {owner:?} }}",
            wire.logical
        ));
        self.b.free(wire.target);
        self.counts.release_r += 1;
    }

    fn require(&self, wire: Wire) {
        assert_eq!(
            self.active.get(&wire.logical).map(|entry| entry.0),
            Some(wire.target)
        );
    }

    fn x(&mut self, target: Wire) {
        self.require(target);
        self.fingerprint(format!("X({})", target.logical));
        self.b.x(target.target);
        self.counts.x += 1;
    }
    fn cx(&mut self, control: Wire, target: Wire) {
        self.require(control);
        self.require(target);
        self.fingerprint(format!("Cx({}, {})", control.logical, target.logical));
        self.b.cx(control.target, target.target);
        self.counts.cx += 1;
    }
    fn ccx(&mut self, a: Wire, c: Wire, target: Wire) {
        self.require(a);
        self.require(c);
        self.require(target);
        self.fingerprint(format!(
            "Ccx({}, {}, {})",
            a.logical, c.logical, target.logical
        ));
        self.b.ccx(a.target, c.target, target.target);
        self.counts.ccx += 1;
    }
    fn swap(&mut self, a: Wire, c: Wire) {
        self.require(a);
        self.require(c);
        self.fingerprint(format!("Swap({}, {})", a.logical, c.logical));
        self.b.swap(a.target, c.target);
        self.counts.swap += 1;
    }

    fn replay_x(&mut self, target: Wire, when: Option<(usize, BitId)>) {
        self.require(target);
        match when {
            None => self.x(target),
            Some((logical_bit, bit)) => {
                self.fingerprint(format!(
                    "ReplayX {{ target: {}, when: Some({logical_bit}) }}",
                    target.logical
                ));
                self.b.x_if(target.target, bit);
                self.counts.x += 1;
            }
        }
    }
    fn replay_cx(&mut self, control: Wire, target: Wire, when: Option<(usize, BitId)>) {
        self.require(control);
        self.require(target);
        match when {
            None => self.cx(control, target),
            Some((logical_bit, bit)) => {
                self.fingerprint(format!(
                    "ReplayCx {{ control: {}, target: {}, when: Some({logical_bit}) }}",
                    control.logical, target.logical
                ));
                self.b.cx_if(control.target, target.target, bit);
                self.counts.cx += 1;
            }
        }
    }
    fn replay_ccx(&mut self, a: Wire, c: Wire, target: Wire, when: Option<(usize, BitId)>) {
        self.require(a);
        self.require(c);
        self.require(target);
        match when {
            None => self.ccx(a, c, target),
            Some((logical_bit, bit)) => {
                self.fingerprint(format!("ReplayCcx {{ control1: {}, control2: {}, target: {}, when: Some({logical_bit}) }}", a.logical, c.logical, target.logical));
                self.b.ccx_if(a.target, c.target, target.target, bit);
                self.counts.ccx += 1;
            }
        }
    }
    fn neg(&mut self, when: Option<(usize, BitId)>) {
        match when {
            None => {
                self.fingerprint("Neg { when: None }".to_string());
                self.b.neg();
            }
            Some((logical_bit, bit)) => {
                self.fingerprint(format!("Neg {{ when: Some({logical_bit}) }}"));
                self.b.neg_if(bit);
            }
        }
        self.counts.neg += 1;
    }
    fn z(&mut self, target: Wire, when: Option<(usize, BitId)>) {
        self.require(target);
        let when_text = when.map(|item| item.0);
        self.fingerprint(format!(
            "Z {{ target: {}, when: {when_text:?} }}",
            target.logical
        ));
        match when {
            None => self.b.z(target.target),
            Some((_, bit)) => self.b.z_if(target.target, bit),
        }
        self.counts.z += 1;
    }
    fn cz(&mut self, control: Wire, target: Wire, when: Option<(usize, BitId)>) {
        self.require(control);
        self.require(target);
        let when_text = when.map(|item| item.0);
        self.fingerprint(format!(
            "Cz {{ control: {}, target: {}, when: {when_text:?} }}",
            control.logical, target.logical
        ));
        match when {
            None => self.b.cz(control.target, target.target),
            Some((_, bit)) => self.b.cz_if(control.target, target.target, bit),
        }
        self.counts.cz += 1;
    }
    fn ccz(&mut self, a: Wire, c: Wire, target: Wire, when: Option<(usize, BitId)>) {
        self.require(a);
        self.require(c);
        self.require(target);
        let when_text = when.map(|item| item.0);
        self.fingerprint(format!(
            "Ccz {{ control1: {}, control2: {}, target: {}, when: {when_text:?} }}",
            a.logical, c.logical, target.logical
        ));
        match when {
            None => self.b.ccz(a.target, c.target, target.target),
            Some((_, bit)) => self.b.ccz_if(a.target, c.target, target.target, bit),
        }
        self.counts.ccz += 1;
    }
    fn hmr(&mut self, target: Wire, output: usize, bit: BitId) {
        self.require(target);
        self.fingerprint(format!(
            "Hmr {{ target: {}, output: {output} }}",
            target.logical
        ));
        self.b.hmr(target.target, bit);
        self.counts.hmr += 1;
    }
    fn reset_z(&mut self, target: Wire) {
        self.require(target);
        self.fingerprint(format!("ResetZ {{ target: {} }}", target.logical));
        self.b.r(target.target);
        self.counts.reset_z += 1;
    }
    fn hmr_reset_cz(&mut self, target: Wire, a: Wire, c: Wire) {
        let logical_bit = self.measurement_bits;
        let bit = self.b.alloc_bit();
        self.measurement_bits += 1;
        self.hmr(target, logical_bit, bit);
        self.reset_z(target);
        self.cz(a, c, Some((logical_bit, bit)));
    }
    fn push_condition(&mut self, logical_bit: usize, bit: BitId) {
        self.fingerprint(format!("PushCondition {{ bit: {logical_bit} }}"));
        self.b.push_condition(bit);
        self.counts.push_condition += 1;
    }
    fn pop_condition(&mut self) {
        self.fingerprint("PopCondition".to_string());
        self.b.pop_condition();
        self.counts.pop_condition += 1;
    }
}

fn number(token: Option<&str>, context: &str) -> Result<usize, String> {
    token
        .ok_or_else(|| format!("missing {context}"))?
        .parse::<usize>()
        .map_err(|error| format!("invalid {context}: {error}"))
}

fn validate_stream(stream: &str, qubits: usize, bits: usize) -> Result<(), String> {
    let mut lines = stream.lines();
    if lines.next() != Some("inactive-binary-gcd-replay-ir/v1") {
        return Err("inactive replay stream version mismatch".to_string());
    }
    for (line_index, line) in lines.enumerate() {
        let mut terms = line.split_ascii_whitespace();
        let opcode = terms
            .next()
            .ok_or_else(|| format!("empty stream line {}", line_index + 2))?;
        let q = |token, context| -> Result<(), String> {
            let value = number(token, context)?;
            if value >= qubits {
                Err(format!("{context} {value} outside {qubits} local qubits"))
            } else {
                Ok(())
            }
        };
        let condition = |token: Option<&str>| -> Result<(), String> {
            let token = token.ok_or_else(|| "missing condition".to_string())?;
            if token != "-" && token.parse::<usize>().map_err(|error| error.to_string())? >= bits {
                return Err(format!("condition {token} outside {bits} bits"));
            }
            Ok(())
        };
        match opcode {
            "x" => {
                q(terms.next(), "x target")?;
                condition(terms.next())?;
            }
            "cx" => {
                q(terms.next(), "cx control")?;
                q(terms.next(), "cx target")?;
                condition(terms.next())?;
            }
            "ccx" => {
                q(terms.next(), "ccx control1")?;
                q(terms.next(), "ccx control2")?;
                q(terms.next(), "ccx target")?;
                condition(terms.next())?;
            }
            "swap" => {
                q(terms.next(), "swap a")?;
                q(terms.next(), "swap b")?;
            }
            "neg" => condition(terms.next())?,
            "z" => {
                q(terms.next(), "z target")?;
                condition(terms.next())?;
            }
            "cz" => {
                q(terms.next(), "cz control")?;
                q(terms.next(), "cz target")?;
                condition(terms.next())?;
            }
            "ccz" => {
                q(terms.next(), "ccz control1")?;
                q(terms.next(), "ccz control2")?;
                q(terms.next(), "ccz target")?;
                condition(terms.next())?;
            }
            "hmr" => {
                q(terms.next(), "hmr target")?;
                if number(terms.next(), "hmr output")? >= bits {
                    return Err("hmr output outside stream".to_string());
                }
            }
            "reset_z" => q(terms.next(), "reset target")?,
            "push_condition" => {
                if number(terms.next(), "pushed condition")? >= bits {
                    return Err("pushed condition outside stream".to_string());
                }
            }
            "pop_condition" => {}
            _ => {
                return Err(format!(
                    "unknown inactive replay opcode {opcode:?} at line {}",
                    line_index + 2
                ))
            }
        }
        if terms.next().is_some() {
            return Err(format!("trailing term at stream line {}", line_index + 2));
        }
    }
    Ok(())
}

fn emit_ir(
    adapter: &mut Adapter<'_>,
    stream: &str,
    wires: &[Wire],
    bit_count: usize,
) -> Result<(), String> {
    let base = adapter.measurement_bits;
    let bits = adapter.b.alloc_bits(bit_count);
    adapter.measurement_bits += bit_count;
    let condition = |token: Option<&str>| -> Result<Option<(usize, BitId)>, String> {
        let token = token.ok_or_else(|| "missing condition".to_string())?;
        if token == "-" {
            return Ok(None);
        }
        let local = token.parse::<usize>().map_err(|error| error.to_string())?;
        Ok(Some((
            base + local,
            *bits
                .get(local)
                .ok_or_else(|| format!("condition bit {local} outside stream"))?,
        )))
    };
    let wire = |index: usize| -> Result<Wire, String> {
        wires
            .get(index)
            .copied()
            .ok_or_else(|| format!("local qubit {index} outside stream"))
    };
    for line in stream.lines().skip(1) {
        let mut term = line.split_ascii_whitespace();
        match term.next().unwrap() {
            "x" => {
                let t = wire(number(term.next(), "x target")?)?;
                let c = condition(term.next())?;
                adapter.replay_x(t, c);
            }
            "cx" => {
                let a = wire(number(term.next(), "cx control")?)?;
                let t = wire(number(term.next(), "cx target")?)?;
                let c = condition(term.next())?;
                adapter.replay_cx(a, t, c);
            }
            "ccx" => {
                let a = wire(number(term.next(), "ccx control1")?)?;
                let c = wire(number(term.next(), "ccx control2")?)?;
                let t = wire(number(term.next(), "ccx target")?)?;
                let when = condition(term.next())?;
                adapter.replay_ccx(a, c, t, when);
            }
            "swap" => {
                let a = wire(number(term.next(), "swap a")?)?;
                let c = wire(number(term.next(), "swap b")?)?;
                adapter.swap(a, c);
            }
            "neg" => {
                let c = condition(term.next())?;
                adapter.neg(c);
            }
            "z" => {
                let t = wire(number(term.next(), "z target")?)?;
                let c = condition(term.next())?;
                adapter.z(t, c);
            }
            "cz" => {
                let a = wire(number(term.next(), "cz control")?)?;
                let t = wire(number(term.next(), "cz target")?)?;
                let c = condition(term.next())?;
                adapter.cz(a, t, c);
            }
            "ccz" => {
                let a = wire(number(term.next(), "ccz control1")?)?;
                let c = wire(number(term.next(), "ccz control2")?)?;
                let t = wire(number(term.next(), "ccz target")?)?;
                let when = condition(term.next())?;
                adapter.ccz(a, c, t, when);
            }
            "hmr" => {
                let t = wire(number(term.next(), "hmr target")?)?;
                let local = number(term.next(), "hmr output")?;
                adapter.hmr(t, base + local, bits[local]);
            }
            "reset_z" => {
                let t = wire(number(term.next(), "reset target")?)?;
                adapter.reset_z(t);
            }
            "push_condition" => {
                let local = number(term.next(), "pushed condition")?;
                adapter.push_condition(base + local, bits[local]);
            }
            "pop_condition" => adapter.pop_condition(),
            opcode => return Err(format!("unsupported validated opcode {opcode}")),
        }
    }
    Ok(())
}

fn mcx3(a: &mut Adapter<'_>, x: Wire, y: Wire, z: Wire, target: Wire, clean: Wire) {
    a.ccx(x, y, clean);
    a.ccx(clean, z, target);
    a.ccx(x, y, clean);
}
fn controlled_maj(a: &mut Adapter<'_>, control: Wire, x: Wire, y: Wire, w: Wire, clean: Wire) {
    a.ccx(control, w, y);
    a.ccx(control, w, x);
    mcx3(a, control, x, y, w, clean);
}
fn controlled_uma(a: &mut Adapter<'_>, control: Wire, x: Wire, y: Wire, w: Wire, clean: Wire) {
    mcx3(a, control, x, y, w, clean);
    a.ccx(control, w, x);
    a.ccx(control, x, y);
}
fn controlled_inv_maj(a: &mut Adapter<'_>, control: Wire, x: Wire, y: Wire, w: Wire, clean: Wire) {
    mcx3(a, control, x, y, w, clean);
    a.ccx(control, w, x);
    a.ccx(control, w, y);
}
fn controlled_inv_uma(a: &mut Adapter<'_>, control: Wire, x: Wire, y: Wire, w: Wire, clean: Wire) {
    a.ccx(control, x, y);
    a.ccx(control, w, x);
    mcx3(a, control, x, y, w, clean);
}

fn controlled_add(
    a: &mut Adapter<'_>,
    addend: &[Wire],
    acc: &[Wire],
    control: Wire,
    _carry: Wire,
    _clean: Wire,
) {
    controlled_clean_add_no_cout(a, addend, acc, control, None, "direct-add-carry");
}
fn controlled_sub(
    a: &mut Adapter<'_>,
    addend: &[Wire],
    acc: &[Wire],
    control: Wire,
    _carry: Wire,
    _clean: Wire,
) {
    // ctrl ? (acc - addend) : acc = controlled add of ~addend with cin=ctrl.
    for &wire in addend {
        a.x(wire);
    }
    let cin = a.acquire_zero("direct-sub-cin".to_string());
    a.cx(control, cin);
    controlled_clean_add_no_cout(
        a,
        addend,
        acc,
        control,
        Some(cin),
        "direct-sub-carry",
    );
    a.cx(control, cin);
    a.release_zero(cin);
    for &wire in addend {
        a.x(wire);
    }
}

/// Fully vented, no-carry-out controlled add.
///
/// This is the unspecialized source shape proved by the prior formal toolset's
/// `GidneyControlledAdd`: `acc += control * (addend + cin) mod 2^n`, with
/// `addend`, `control`, and `cin` preserved. There are `n-1` clean carry lanes,
/// `n-1` forward carry CCX, and `n` controlled-sum CCX, hence `2n-1` total.
/// The reverse carry clear is explicit HMR, reset, and conditional CZ; this
/// function must never be obtained by reversing an emitted measurement stream.
fn controlled_clean_add_no_cout(
    a: &mut Adapter<'_>,
    addend: &[Wire],
    acc: &[Wire],
    control: Wire,
    cin: Option<Wire>,
    owner: &str,
) {
    let n = addend.len();
    assert_eq!(n, acc.len());
    assert!(n > 0);
    let carries: Vec<_> = (0..n - 1)
        .map(|bit| a.acquire_zero(format!("{owner}[{bit}]")))
        .collect();

    for i in 0..n - 1 {
        let carry_in = if i == 0 { cin } else { Some(carries[i - 1]) };
        if let Some(carry_in) = carry_in {
            a.cx(carry_in, acc[i]);
            a.cx(carry_in, addend[i]);
            a.ccx(acc[i], addend[i], carries[i]);
            a.cx(carry_in, carries[i]);
        } else {
            a.ccx(acc[i], addend[i], carries[i]);
        }
    }

    for i in (0..n).rev() {
        let carry_in = if i == 0 { cin } else { Some(carries[i - 1]) };
        if i + 1 == n {
            if let Some(carry_in) = carry_in {
                a.cx(carry_in, addend[i]);
            }
            a.ccx(control, addend[i], acc[i]);
            if let Some(carry_in) = carry_in {
                a.cx(carry_in, addend[i]);
            }
            continue;
        }

        let carry_out = carries[i];
        if let Some(carry_in) = carry_in {
            a.cx(carry_in, carry_out);
        }
        a.hmr_reset_cz(carry_out, acc[i], addend[i]);
        if let Some(carry_in) = carry_in {
            a.cx(carry_in, acc[i]);
        }
        a.ccx(control, addend[i], acc[i]);
        if let Some(carry_in) = carry_in {
            a.cx(carry_in, addend[i]);
        }
        a.release_zero(carry_out);
    }
}
fn lt_xor(a: &mut Adapter<'_>, left: &[Wire], right: &[Wire], flag: Wire, carry: Wire) {
    assert_eq!(left.len(), right.len());
    assert!(!left.is_empty());
    let carries: Vec<_> = (0..left.len())
        .map(|bit| a.acquire_zero(format!("lt-gidney-carry[{bit}]")))
        .collect();
    for &wire in left {
        a.x(wire);
    }
    a.cx(left[0], right[0]);
    a.cx(left[0], carry);
    a.ccx(carry, right[0], carries[0]);
    a.cx(carries[0], left[0]);
    for i in 1..left.len() {
        a.cx(left[i], right[i]);
        a.cx(left[i], left[i - 1]);
        a.ccx(left[i - 1], right[i], carries[i]);
        a.cx(carries[i], left[i]);
    }
    a.cx(left[left.len() - 1], flag);
    for i in (1..left.len()).rev() {
        a.cx(carries[i], left[i]);
        a.hmr_reset_cz(carries[i], left[i - 1], right[i]);
        a.cx(left[i], left[i - 1]);
        a.cx(left[i], right[i]);
        a.release_zero(carries[i]);
    }
    a.cx(carries[0], left[0]);
    a.hmr_reset_cz(carries[0], carry, right[0]);
    a.cx(left[0], carry);
    a.cx(left[0], right[0]);
    a.release_zero(carries[0]);
    for &wire in left {
        a.x(wire);
    }
}
fn controlled_swap_word(a: &mut Adapter<'_>, left: &[Wire], right: &[Wire], control: Wire) {
    for (&x, &y) in left.iter().zip(right) {
        a.cx(y, x);
        a.ccx(control, x, y);
        a.cx(y, x);
    }
}
fn shift_right(a: &mut Adapter<'_>, word: &[Wire]) {
    for i in 0..word.len() - 1 {
        a.swap(word[i], word[i + 1]);
    }
}
fn shift_right_inverse(a: &mut Adapter<'_>, word: &[Wire]) {
    for i in (0..word.len() - 1).rev() {
        a.swap(word[i], word[i + 1]);
    }
}

fn selector(
    a: &mut Adapter<'_>,
    u: &[Wire],
    v: &[Wire],
    b0: Wire,
    swap_sub: Wire,
    predicate: Wire,
    carry: Wire,
) {
    a.cx(v[0], b0);
    lt_xor(a, v, u, predicate, carry);
    a.ccx(b0, predicate, swap_sub);
    lt_xor(a, v, u, predicate, carry);
}
fn clear_selector(
    a: &mut Adapter<'_>,
    u: &[Wire],
    v: &[Wire],
    b0: Wire,
    swap_sub: Wire,
    predicate: Wire,
    carry: Wire,
) {
    lt_xor(a, v, u, predicate, carry);
    a.ccx(b0, predicate, swap_sub);
    lt_xor(a, v, u, predicate, carry);
    a.cx(v[0], b0);
}
fn forward_step(a: &mut Adapter<'_>, u: &[Wire], v: &[Wire], pair: [Wire; 2], scratch: [Wire; 2]) {
    selector(a, u, v, pair[0], pair[1], scratch[0], scratch[1]);
    controlled_swap_word(a, u, v, pair[1]);
    controlled_sub(a, u, v, pair[0], scratch[0], scratch[1]);
    shift_right(a, v);
}
fn inverse_step(a: &mut Adapter<'_>, u: &[Wire], v: &[Wire], pair: [Wire; 2], scratch: [Wire; 2]) {
    shift_right_inverse(a, v);
    controlled_add(a, u, v, pair[0], scratch[0], scratch[1]);
    controlled_swap_word(a, u, v, pair[1]);
    clear_selector(a, u, v, pair[0], pair[1], scratch[0], scratch[1]);
}

fn figure1_pack(a: &mut Adapter<'_>, w: [Wire; 6]) {
    a.cx(w[1], w[0]);
    a.cx(w[3], w[2]);
    a.cx(w[5], w[4]);
    a.cx(w[0], w[2]);
    a.cx(w[5], w[3]);
    a.x(w[4]);
    a.ccx(w[1], w[3], w[5]);
    a.cx(w[1], w[4]);
    a.x(w[2]);
    a.ccx(w[3], w[4], w[5]);
    a.ccx(w[4], w[5], w[1]);
    a.ccx(w[2], w[5], w[0]);
    a.ccx(w[0], w[1], w[5]);
}
fn figure1_unpack(a: &mut Adapter<'_>, w: [Wire; 6]) {
    a.ccx(w[0], w[1], w[5]);
    a.ccx(w[2], w[5], w[0]);
    a.ccx(w[4], w[5], w[1]);
    a.ccx(w[3], w[4], w[5]);
    a.x(w[2]);
    a.cx(w[1], w[4]);
    a.ccx(w[1], w[3], w[5]);
    a.x(w[4]);
    a.cx(w[5], w[3]);
    a.cx(w[0], w[2]);
    a.cx(w[5], w[4]);
    a.cx(w[3], w[2]);
    a.cx(w[1], w[0]);
}
fn component_width(round: usize) -> usize {
    WIDTH.min(2 * WIDTH - round)
}

fn emit_raw_replay(
    a: &mut Adapter<'_>,
    r: &[Wire],
    s: &[Wire],
    pair: [Wire; 2],
    scratch: &[Wire],
    carries: &[Wire],
) -> Result<(), String> {
    let mut wires = Vec::with_capacity(3 * WIDTH + 2 + 7);
    wires.extend_from_slice(r);
    wires.extend_from_slice(s);
    wires.extend_from_slice(&pair);
    wires.extend_from_slice(scratch);
    wires.extend_from_slice(carries);
    emit_ir(a, RAW_STREAM, &wires, RAW_MEASUREMENT_BITS)
}
fn emit_reverse_triple(
    a: &mut Adapter<'_>,
    r: &[Wire],
    s: &[Wire],
    packed: [Wire; 5],
    scratch: &[Wire],
    carries: &[Wire],
) -> Result<(), String> {
    let mut wires = Vec::with_capacity(3 * WIDTH + 5 + 7);
    wires.extend_from_slice(r);
    wires.extend_from_slice(s);
    wires.extend_from_slice(&packed);
    wires.extend_from_slice(scratch);
    wires.extend_from_slice(carries);
    emit_ir(a, REVERSE_TRIPLE_STREAM, &wires, TRIPLE_MEASUREMENT_BITS)
}
fn emit_inverse_raw_replay(
    a: &mut Adapter<'_>,
    r: &[Wire],
    s: &[Wire],
    threshold: &[Wire],
    pair: [Wire; 2],
    scratch: &[Wire],
) -> Result<(), String> {
    let mut wires = Vec::with_capacity(3 * WIDTH + 2 + 6);
    wires.extend_from_slice(r);
    wires.extend_from_slice(s);
    wires.extend_from_slice(threshold);
    wires.extend_from_slice(&pair);
    wires.extend_from_slice(scratch);
    emit_ir(a, INVERSE_RAW_STREAM, &wires, INVERSE_RAW_MEASUREMENT_BITS)
}
fn emit_inverse_triple(
    a: &mut Adapter<'_>,
    r: &[Wire],
    s: &[Wire],
    threshold: &[Wire],
    packed: [Wire; 5],
    scratch: &[Wire],
) -> Result<(), String> {
    let mut wires = Vec::with_capacity(3 * WIDTH + 5 + 7);
    wires.extend_from_slice(r);
    wires.extend_from_slice(s);
    wires.extend_from_slice(threshold);
    wires.extend_from_slice(&packed);
    wires.extend_from_slice(scratch);
    emit_ir(
        a,
        INVERSE_TRIPLE_STREAM,
        &wires,
        INVERSE_TRIPLE_MEASUREMENT_BITS,
    )
}

fn sha3_target_ops(ops: &[Op]) -> String {
    let mut hasher = Sha3_256::new();
    for op in ops {
        op.validate();
        let mut rec = [0u8; 56];
        rec[0..4].copy_from_slice(&(op.kind as u32).to_le_bytes());
        rec[8..16].copy_from_slice(&op.q_control2.0.to_le_bytes());
        rec[16..24].copy_from_slice(&op.q_control1.0.to_le_bytes());
        rec[24..32].copy_from_slice(&op.q_target.0.to_le_bytes());
        rec[32..40].copy_from_slice(&op.c_target.0.to_le_bytes());
        rec[40..48].copy_from_slice(&op.c_condition.0.to_le_bytes());
        rec[48..56].copy_from_slice(&op.r_target.0.to_le_bytes());
        hasher.update(rec);
    }
    hasher
        .finalize()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

/// Forward orientation `(x,y) -> (x,x*y)` for canonical nonzero `x`.
pub(super) fn emit_inactive_binary_gcd_in_place(
    b: &mut B,
    x: &[QubitId],
    y: &[QubitId],
) -> Result<BindingReport, String> {
    validate_stream(RAW_STREAM, 3 * WIDTH + 2 + 7, RAW_MEASUREMENT_BITS)?;
    validate_stream(
        REVERSE_TRIPLE_STREAM,
        3 * WIDTH + 5 + 7,
        TRIPLE_MEASUREMENT_BITS,
    )?;
    let start_ops = b.ops.len();
    let x_targets = x.to_vec();
    let y_targets = y.to_vec();
    let mut a = Adapter::new(b, &x_targets, &y_targets)?;
    let y_wires: Vec<_> = (0..WIDTH)
        .map(|logical| Wire {
            logical,
            target: y_targets[logical],
        })
        .collect();
    let original_v: Vec<_> = (0..WIDTH)
        .map(|bit| Wire {
            logical: WIDTH + bit,
            target: x_targets[bit],
        })
        .collect();
    let original_u: Vec<_> = (0..WIDTH)
        .map(|bit| a.acquire_zero(format!("value-u[{bit}]")))
        .collect();
    let mut u = original_u.clone();
    let mut v = original_v.clone();
    let modulus = [
        0xffff_fffe_ffff_fc2fu64,
        0xffff_ffff_ffff_ffff,
        0xffff_ffff_ffff_ffff,
        0xffff_ffff_ffff_ffff,
    ];
    for (bit, &wire) in original_u.iter().enumerate() {
        if (modulus[bit / 64] >> (bit % 64)) & 1 != 0 {
            a.x(wire);
        }
    }

    let mut pairs = Vec::<[Wire; 2]>::with_capacity(ROUNDS);
    let mut released_u = vec![None; ROUNDS];
    let mut released_v = vec![None; ROUNDS];
    for round in 0..ROUNDS {
        let pair = [
            a.acquire_zero(format!("tape-raw[{round}].b0")),
            a.acquire_zero(format!("tape-raw[{round}].swap")),
        ];
        let scratch = [
            a.acquire_zero(format!("forward-scratch[{round}].predicate")),
            a.acquire_zero(format!("forward-scratch[{round}].carry")),
        ];
        forward_step(&mut a, &u, &v, pair, scratch);
        a.release_zero(scratch[1]);
        a.release_zero(scratch[0]);
        pairs.push(pair);
        if round % 3 == 2 {
            let word = [
                pairs[round - 2][0],
                pairs[round - 2][1],
                pairs[round - 1][0],
                pairs[round - 1][1],
                pairs[round][0],
                pairs[round][1],
            ];
            figure1_pack(&mut a, word);
            a.release_zero(word[5]);
        }
        let next_width = component_width(round + 1);
        if next_width < u.len() {
            let uw = u.pop().unwrap();
            let vw = v.pop().unwrap();
            released_u[round] = Some(uw);
            released_v[round] = Some(vw);
            a.release_zero(uw);
            a.release_zero(vw);
        }
    }
    a.x(u[0]);
    a.release_zero(u[0]);
    a.release_zero(v[0]);

    let replay_s: Vec<_> = (0..WIDTH)
        .map(|bit| a.acquire_zero(format!("replay-s[{bit}]")))
        .collect();
    let replay_scratch: Vec<_> = (0..7)
        .map(|bit| a.acquire_zero(format!("replay-scratch[{bit}]")))
        .collect();
    let replay_carries: Vec<_> = (0..WIDTH)
        .map(|bit| a.acquire_zero(format!("replay-gidney-carry[{bit}]")))
        .collect();
    emit_raw_replay(
        &mut a,
        &y_wires,
        &replay_s,
        pairs[ROUNDS - 1],
        &replay_scratch,
        &replay_carries,
    )?;
    for group in (0..ROUNDS / 3).rev() {
        let start = 3 * group;
        let packed = [
            pairs[start][0],
            pairs[start][1],
            pairs[start + 1][0],
            pairs[start + 1][1],
            pairs[start + 2][0],
        ];
        emit_reverse_triple(
            &mut a,
            &y_wires,
            &replay_s,
            packed,
            &replay_scratch,
            &replay_carries,
        )?;
    }
    for (&r, &s) in y_wires.iter().zip(&replay_s) {
        a.swap(r, s);
    }
    for wire in replay_scratch.into_iter().rev() {
        a.release_zero(wire);
    }
    for wire in replay_carries.into_iter().rev() {
        a.release_zero(wire);
    }
    for wire in replay_s.into_iter().rev() {
        a.release_zero(wire);
    }

    a.acquire_specific(original_u[0], "inverse-u[0]".to_string());
    a.acquire_specific(original_v[0], "inverse-v[0]".to_string());
    a.x(original_u[0]);
    u = vec![original_u[0]];
    v = vec![original_v[0]];
    for round in (0..ROUNDS).rev() {
        if let Some(wire) = released_u[round] {
            let bit = u.len();
            a.acquire_specific(wire, format!("inverse-u[{bit}]"));
            u.push(wire);
        }
        if let Some(wire) = released_v[round] {
            let bit = v.len();
            a.acquire_specific(wire, format!("inverse-v[{bit}]"));
            v.push(wire);
        }
        if round % 3 == 2 {
            let sixth = pairs[round][1];
            a.acquire_specific(sixth, format!("tape-decode[{round}]"));
            figure1_unpack(
                &mut a,
                [
                    pairs[round - 2][0],
                    pairs[round - 2][1],
                    pairs[round - 1][0],
                    pairs[round - 1][1],
                    pairs[round][0],
                    pairs[round][1],
                ],
            );
        }
        let scratch = [
            a.acquire_zero(format!("inverse-scratch[{round}].predicate")),
            a.acquire_zero(format!("inverse-scratch[{round}].carry")),
        ];
        inverse_step(&mut a, &u, &v, pairs[round], scratch);
        a.release_zero(scratch[1]);
        a.release_zero(scratch[0]);
        a.release_zero(pairs[round][1]);
        a.release_zero(pairs[round][0]);
    }
    for (bit, &wire) in original_u.iter().enumerate() {
        if (modulus[bit / 64] >> (bit % 64)) & 1 != 0 {
            a.x(wire);
        }
    }
    for &wire in original_u.iter().rev() {
        a.release_zero(wire);
    }
    let expected: BTreeSet<_> = original_v
        .iter()
        .chain(&y_wires)
        .map(|wire| wire.logical)
        .collect();
    assert_eq!(a.active.keys().copied().collect::<BTreeSet<_>>(), expected);

    let lifecycle_fnv1a128 = format!("{:032x}", a.lifecycle_fnv1a128);
    let lifecycle_operations = a.lifecycle_operations;
    let measurement_bits = a.measurement_bits;
    let counts = a.counts;
    let peak_qubits = a.b.peak_qubits;
    let total_qubit_ids = a.b.next_qubit;
    drop(a);
    let target_ops = &b.ops[start_ops..];
    Ok(BindingReport {
        target_operations: target_ops.len(),
        target_operation_sha3_256: sha3_target_ops(target_ops),
        lifecycle_operations,
        lifecycle_fnv1a128,
        measurement_bits,
        peak_qubits,
        total_qubit_ids,
        counts,
    })
}

/// Inactive explicit inverse orientation `(x,y) -> (x,y/x)` for nonzero `x`.
/// The value walk is unchanged, but coefficient replay consumes the tape in
/// forward order using separately lowered subtraction and canonical halving.
pub(super) fn emit_inactive_binary_gcd_inverse_in_place(
    b: &mut B,
    x: &[QubitId],
    y: &[QubitId],
) -> Result<BindingReport, String> {
    validate_stream(
        INVERSE_RAW_STREAM,
        3 * WIDTH + 2 + 6,
        INVERSE_RAW_MEASUREMENT_BITS,
    )?;
    validate_stream(
        INVERSE_TRIPLE_STREAM,
        3 * WIDTH + 5 + 7,
        INVERSE_TRIPLE_MEASUREMENT_BITS,
    )?;
    let start_ops = b.ops.len();
    let x_targets = x.to_vec();
    let y_targets = y.to_vec();
    let mut a = Adapter::new(b, &x_targets, &y_targets)?;
    let y_wires: Vec<_> = (0..WIDTH)
        .map(|logical| Wire { logical, target: y_targets[logical] })
        .collect();
    let original_v: Vec<_> = (0..WIDTH)
        .map(|bit| Wire { logical: WIDTH + bit, target: x_targets[bit] })
        .collect();
    let original_u: Vec<_> = (0..WIDTH)
        .map(|bit| a.acquire_zero(format!("value-u[{bit}]")))
        .collect();
    let mut u = original_u.clone();
    let mut v = original_v.clone();
    let modulus = [
        0xffff_fffe_ffff_fc2fu64,
        0xffff_ffff_ffff_ffff,
        0xffff_ffff_ffff_ffff,
        0xffff_ffff_ffff_ffff,
    ];
    for (bit, &wire) in original_u.iter().enumerate() {
        if (modulus[bit / 64] >> (bit % 64)) & 1 != 0 {
            a.x(wire);
        }
    }

    let mut pairs = Vec::<[Wire; 2]>::with_capacity(ROUNDS);
    let mut released_u = vec![None; ROUNDS];
    let mut released_v = vec![None; ROUNDS];
    for round in 0..ROUNDS {
        let pair = [
            a.acquire_zero(format!("tape-raw[{round}].b0")),
            a.acquire_zero(format!("tape-raw[{round}].swap")),
        ];
        let scratch = [
            a.acquire_zero(format!("forward-scratch[{round}].predicate")),
            a.acquire_zero(format!("forward-scratch[{round}].carry")),
        ];
        forward_step(&mut a, &u, &v, pair, scratch);
        a.release_zero(scratch[1]);
        a.release_zero(scratch[0]);
        pairs.push(pair);
        if round % 3 == 2 {
            let word = [
                pairs[round - 2][0], pairs[round - 2][1],
                pairs[round - 1][0], pairs[round - 1][1],
                pairs[round][0], pairs[round][1],
            ];
            figure1_pack(&mut a, word);
            a.release_zero(word[5]);
        }
        let next_width = component_width(round + 1);
        if next_width < u.len() {
            let uw = u.pop().unwrap();
            let vw = v.pop().unwrap();
            released_u[round] = Some(uw);
            released_v[round] = Some(vw);
            a.release_zero(uw);
            a.release_zero(vw);
        }
    }
    a.x(u[0]);
    a.release_zero(u[0]);
    a.release_zero(v[0]);

    // Caller-independent canonical threshold used to erase halve parity.
    let threshold: Vec<_> = (0..WIDTH)
        .map(|bit| a.acquire_zero(format!("halve-threshold[{bit}]")))
        .collect();
    let threshold_words = [
        0xffff_ffff_7fff_fe18u64,
        0xffff_ffff_ffff_ffff,
        0xffff_ffff_ffff_ffff,
        0x7fff_ffff_ffff_ffff,
    ];
    for (bit, &wire) in threshold.iter().enumerate() {
        if (threshold_words[bit / 64] >> (bit % 64)) & 1 != 0 {
            a.x(wire);
        }
    }
    let replay_r: Vec<_> = (0..WIDTH)
        .map(|bit| a.acquire_zero(format!("inverse-replay-r[{bit}]")))
        .collect();
    let replay_scratch: Vec<_> = (0..7)
        .map(|bit| a.acquire_zero(format!("inverse-replay-scratch[{bit}]")))
        .collect();
    for group in 0..ROUNDS / 3 {
        let start = 3 * group;
        let packed = [
            pairs[start][0], pairs[start][1], pairs[start + 1][0],
            pairs[start + 1][1], pairs[start + 2][0],
        ];
        emit_inverse_triple(
            &mut a,
            &replay_r,
            &y_wires,
            &threshold,
            packed,
            &replay_scratch,
        )?;
    }
    emit_inverse_raw_replay(
        &mut a,
        &replay_r,
        &y_wires,
        &threshold,
        pairs[ROUNDS - 1],
        &replay_scratch[..6],
    )?;
    for (&r, &s) in replay_r.iter().zip(&y_wires) {
        a.swap(r, s);
    }
    for wire in replay_scratch.into_iter().rev() {
        a.release_zero(wire);
    }
    for wire in replay_r.into_iter().rev() {
        a.release_zero(wire);
    }
    for (bit, &wire) in threshold.iter().enumerate() {
        if (threshold_words[bit / 64] >> (bit % 64)) & 1 != 0 {
            a.x(wire);
        }
    }
    for wire in threshold.into_iter().rev() {
        a.release_zero(wire);
    }

    a.acquire_specific(original_u[0], "inverse-u[0]".to_string());
    a.acquire_specific(original_v[0], "inverse-v[0]".to_string());
    a.x(original_u[0]);
    u = vec![original_u[0]];
    v = vec![original_v[0]];
    for round in (0..ROUNDS).rev() {
        if let Some(wire) = released_u[round] {
            let bit = u.len();
            a.acquire_specific(wire, format!("inverse-u[{bit}]"));
            u.push(wire);
        }
        if let Some(wire) = released_v[round] {
            let bit = v.len();
            a.acquire_specific(wire, format!("inverse-v[{bit}]"));
            v.push(wire);
        }
        if round % 3 == 2 {
            let sixth = pairs[round][1];
            a.acquire_specific(sixth, format!("tape-decode[{round}]"));
            figure1_unpack(&mut a, [
                pairs[round - 2][0], pairs[round - 2][1],
                pairs[round - 1][0], pairs[round - 1][1],
                pairs[round][0], pairs[round][1],
            ]);
        }
        let scratch = [
            a.acquire_zero(format!("inverse-scratch[{round}].predicate")),
            a.acquire_zero(format!("inverse-scratch[{round}].carry")),
        ];
        inverse_step(&mut a, &u, &v, pairs[round], scratch);
        a.release_zero(scratch[1]);
        a.release_zero(scratch[0]);
        a.release_zero(pairs[round][1]);
        a.release_zero(pairs[round][0]);
    }
    for (bit, &wire) in original_u.iter().enumerate() {
        if (modulus[bit / 64] >> (bit % 64)) & 1 != 0 {
            a.x(wire);
        }
    }
    for &wire in original_u.iter().rev() {
        a.release_zero(wire);
    }
    let expected: BTreeSet<_> = original_v.iter().chain(&y_wires)
        .map(|wire| wire.logical).collect();
    assert_eq!(a.active.keys().copied().collect::<BTreeSet<_>>(), expected);

    let lifecycle_fnv1a128 = format!("{:032x}", a.lifecycle_fnv1a128);
    let lifecycle_operations = a.lifecycle_operations;
    let measurement_bits = a.measurement_bits;
    let counts = a.counts;
    let peak_qubits = a.b.peak_qubits;
    let total_qubit_ids = a.b.next_qubit;
    drop(a);
    let target_ops = &b.ops[start_ops..];
    Ok(BindingReport {
        target_operations: target_ops.len(),
        target_operation_sha3_256: sha3_target_ops(target_ops),
        lifecycle_operations,
        lifecycle_fnv1a128,
        measurement_bits,
        peak_qubits,
        total_qubit_ids,
        counts,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use quantum_ecc::sim::Simulator;
    use sha3::{digest::ExtendableOutput, Shake256};

    fn apply_value_ops(ops: &[Op], state: &mut [bool]) {
        for op in ops {
            let q = |wire: QubitId| wire.0 as usize;
            match op.kind {
                OperationType::X => state[q(op.q_target)] ^= true,
                OperationType::CX => {
                    if state[q(op.q_control1)] {
                        state[q(op.q_target)] ^= true;
                    }
                }
                OperationType::CCX => {
                    if state[q(op.q_control1)] && state[q(op.q_control2)] {
                        state[q(op.q_target)] ^= true;
                    }
                }
                OperationType::Swap => {
                    state.swap(q(op.q_control1), q(op.q_target));
                }
                OperationType::R | OperationType::Hmr => {
                    state[q(op.q_target)] = false;
                }
                OperationType::Neg
                | OperationType::Z
                | OperationType::CZ
                | OperationType::CCZ => {}
                kind => panic!("unexpected value-test operation {kind:?}"),
            }
        }
    }

    fn primitive_circuit(n: usize, subtract: bool) -> (B, Vec<QubitId>, Vec<QubitId>) {
        let mut b = B::new();
        let y = b.alloc_qubits(WIDTH);
        let x = b.alloc_qubits(WIDTH);
        {
            let mut a = Adapter::new(&mut b, &x, &y).unwrap();
            let addend: Vec<_> = (0..n)
                .map(|bit| Wire { logical: bit, target: y[bit] })
                .collect();
            let acc: Vec<_> = (0..n)
                .map(|bit| Wire { logical: WIDTH + bit, target: x[bit] })
                .collect();
            let control = Wire { logical: WIDTH + n, target: x[n] };
            let scratch = [
                a.acquire_zero("test-scratch-0".to_string()),
                a.acquire_zero("test-scratch-1".to_string()),
            ];
            let before = a.counts.ccx;
            if subtract {
                controlled_sub(&mut a, &addend, &acc, control, scratch[0], scratch[1]);
            } else {
                controlled_add(&mut a, &addend, &acc, control, scratch[0], scratch[1]);
            }
            assert_eq!(a.counts.ccx - before, 2 * n - 1);
            a.release_zero(scratch[1]);
            a.release_zero(scratch[0]);
            assert_eq!(a.active.len(), 2 * WIDTH);
        }
        (b, y, x)
    }

    fn comparator_circuit(n: usize) -> (B, Vec<QubitId>, Vec<QubitId>, QubitId) {
        let mut b = B::new();
        let y = b.alloc_qubits(WIDTH);
        let x = b.alloc_qubits(WIDTH);
        let flag = x[n];
        {
            let mut a = Adapter::new(&mut b, &x, &y).unwrap();
            let left: Vec<_> = (0..n)
                .map(|bit| Wire { logical: bit, target: y[bit] })
                .collect();
            let right: Vec<_> = (0..n)
                .map(|bit| Wire { logical: WIDTH + bit, target: x[bit] })
                .collect();
            let carry = a.acquire_zero("test-lt-carry".to_string());
            let before = a.counts.ccx;
            lt_xor(
                &mut a,
                &left,
                &right,
                Wire { logical: WIDTH + n, target: flag },
                carry,
            );
            assert_eq!(a.counts.ccx - before, n);
            a.release_zero(carry);
            assert_eq!(a.active.len(), 2 * WIDTH);
        }
        (b, y, x, flag)
    }

    #[test]
    fn loan_aware_comparator_exhaustive_small_width() {
        for n in 1..=6 {
            let (b, left_word, right_word, flag) = comparator_circuit(n);
            let modulus = 1usize << n;
            for initial_flag in [false, true] {
                for left in 0..modulus {
                    for right in 0..modulus {
                        let mut state = vec![false; b.next_qubit as usize];
                        for bit in 0..n {
                            state[left_word[bit].0 as usize] = (left >> bit) & 1 != 0;
                            state[right_word[bit].0 as usize] = (right >> bit) & 1 != 0;
                        }
                        state[flag.0 as usize] = initial_flag;
                        apply_value_ops(&b.ops, &mut state);
                        assert_eq!(state[flag.0 as usize], initial_flag ^ (left < right));
                        for bit in 0..n {
                            assert_eq!(state[left_word[bit].0 as usize], (left >> bit) & 1 != 0);
                            assert_eq!(state[right_word[bit].0 as usize], (right >> bit) & 1 != 0);
                        }
                        assert!(state[2 * WIDTH..].iter().all(|&bit| !bit));
                    }
                }
            }
        }
    }

    #[test]
    fn loan_aware_comparator_sampled_branch_phase() {
        use sha3::digest::Update;

        for n in 1..=4 {
            let (b, left_word, right_word, flag) = comparator_circuit(n);
            let mut shake = Shake256::default();
            shake.update(&[0xc7, n as u8]);
            let mut xof = shake.finalize_xof();
            let mut sim = Simulator::new(b.next_qubit as usize, b.next_bit as usize, &mut xof);
            let modulus = 1usize << n;
            for initial_flag in [false, true] {
                for left in 0..modulus {
                    for right in 0..modulus {
                        sim.clear_for_shot();
                        for bit in 0..n {
                            sim.qubits[left_word[bit].0 as usize] =
                                if (left >> bit) & 1 != 0 { u64::MAX } else { 0 };
                            sim.qubits[right_word[bit].0 as usize] =
                                if (right >> bit) & 1 != 0 { u64::MAX } else { 0 };
                        }
                        sim.qubits[flag.0 as usize] = if initial_flag { u64::MAX } else { 0 };
                        sim.apply_iter(b.ops.iter());
                        assert_eq!(sim.phase, 0, "branch phase at n={n}");
                        assert!(sim.qubits[2 * WIDTH..].iter().all(|&word| word == 0));
                    }
                }
            }
        }
    }

    #[test]
    fn loan_aware_controlled_add_sub_exhaustive_small_width() {
        for subtract in [false, true] {
            for n in 1..=6 {
                let (b, addend_word, acc_word) = primitive_circuit(n, subtract);
                let modulus = 1usize << n;
                for control in [false, true] {
                    for addend in 0..modulus {
                        for acc in 0..modulus {
                            let mut state = vec![false; b.next_qubit as usize];
                            for bit in 0..n {
                                state[addend_word[bit].0 as usize] = (addend >> bit) & 1 != 0;
                                state[acc_word[bit].0 as usize] = (acc >> bit) & 1 != 0;
                            }
                            state[acc_word[n].0 as usize] = control;
                            apply_value_ops(&b.ops, &mut state);

                            let got_addend = (0..n).fold(0usize, |value, bit| {
                                value | ((state[addend_word[bit].0 as usize] as usize) << bit)
                            });
                            let got_acc = (0..n).fold(0usize, |value, bit| {
                                value | ((state[acc_word[bit].0 as usize] as usize) << bit)
                            });
                            let expected_acc = if !control {
                                acc
                            } else if subtract {
                                acc.wrapping_sub(addend) % modulus
                            } else {
                                (acc + addend) % modulus
                            };
                            assert_eq!(got_addend, addend);
                            assert_eq!(got_acc, expected_acc);
                            assert_eq!(state[acc_word[n].0 as usize], control);
                            assert!(state[2 * WIDTH..].iter().all(|&bit| !bit));
                        }
                    }
                }
            }
        }
    }

    #[test]
    fn loan_aware_controlled_add_sub_sampled_branch_phase() {
        use sha3::digest::Update;

        for subtract in [false, true] {
            for n in 1..=4 {
                let (b, addend_word, acc_word) = primitive_circuit(n, subtract);
                let mut shake = Shake256::default();
                shake.update(&[subtract as u8, n as u8]);
                let mut xof = shake.finalize_xof();
                let mut sim = Simulator::new(
                    b.next_qubit as usize,
                    b.next_bit as usize,
                    &mut xof,
                );
                let modulus = 1usize << n;
                for control in [false, true] {
                    for addend in 0..modulus {
                        for acc in 0..modulus {
                            sim.clear_for_shot();
                            for bit in 0..n {
                                sim.qubits[addend_word[bit].0 as usize] =
                                    if (addend >> bit) & 1 != 0 { u64::MAX } else { 0 };
                                sim.qubits[acc_word[bit].0 as usize] =
                                    if (acc >> bit) & 1 != 0 { u64::MAX } else { 0 };
                            }
                            sim.qubits[acc_word[n].0 as usize] =
                                if control { u64::MAX } else { 0 };
                            sim.apply_iter(b.ops.iter());

                            assert_eq!(sim.phase, 0, "branch phase at n={n}");
                            assert!(sim.qubits[2 * WIDTH..].iter().all(|&word| word == 0));
                        }
                    }
                }
            }
        }
    }

    #[test]
    fn malformed_inputs_fail_before_target_emission() {
        let mut b = B::new();
        let word = b.alloc_qubits(WIDTH);
        let error = emit_inactive_binary_gcd_in_place(&mut b, &word, &word).unwrap_err();
        assert!(error.contains("alias"));
        assert!(b.ops.is_empty());
    }

    #[test]
    #[ignore = "full 24.0M-operation binding receipt; run explicitly in release mode"]
    fn complete_target_binding_is_frozen() {
        let mut b = B::new();
        let y = b.alloc_qubits(WIDTH);
        let x = b.alloc_qubits(WIDTH);
        let report = emit_inactive_binary_gcd_in_place(&mut b, &x, &y).unwrap();
        assert_eq!(report.lifecycle_operations, 23_959_727);
        assert_eq!(report.lifecycle_fnv1a128, EXPECTED_LIFECYCLE_FNV1A128);
        assert_eq!(report.measurement_bits, 1_503_232);
        assert_eq!(report.peak_qubits, 1_627);
        assert_eq!(report.total_qubit_ids, 1_627);
        assert_eq!(report.target_operations, 23_364_617);
        assert_eq!(
            report.target_operation_sha3_256,
            "2bbcc3c56887cee7696da58655de24162bf18d5599ff7939337d653778214820"
        );
        assert_eq!(report.counts.x, 2_680_648);
        assert_eq!(report.counts.cx, 11_002_829);
        assert_eq!(report.counts.ccx, 3_722_582);
        assert_eq!(report.counts.swap, 326_912);
        assert_eq!(report.counts.z, 1_042_440);
        assert_eq!(report.counts.cz, 982_012);
        assert_eq!(report.counts.hmr, 1_503_232);
        assert_eq!(report.counts.reset_z, 1_509_364);
        assert_eq!(report.counts.release_r, 594_598);
        assert_eq!(b.active_qubits, 512);
        assert_eq!(b.next_bit, 1_503_232);
        assert!(b.ops.iter().all(|op| {
            op.validate();
            op.q_target != NO_QUBIT
                || op.q_control1 != NO_QUBIT
                || op.q_control2 != NO_QUBIT
                || op.c_target != NO_BIT
                || op.c_condition != NO_BIT
                || op.r_target != NO_REG
                || op.kind == OperationType::Neg
                || op.kind == OperationType::PopCondition
        }));
        println!(
            "target_operation_sha3_256={}",
            report.target_operation_sha3_256
        );
    }

    #[test]
    #[ignore = "full loan-aware forward/replay target report"]
    fn loan_aware_complete_target_report() {
        let mut b = B::new();
        let y = b.alloc_qubits(WIDTH);
        let x = b.alloc_qubits(WIDTH);
        let report = emit_inactive_binary_gcd_in_place(&mut b, &x, &y).unwrap();
        assert_eq!(report.counts.ccx, 3_722_582);
        assert_eq!(report.peak_qubits, 1_627);
        assert_eq!(b.active_qubits, 512);
        assert!(b.ops.iter().all(|op| {
            op.validate();
            op.q_target != NO_QUBIT
                || op.q_control1 != NO_QUBIT
                || op.q_control2 != NO_QUBIT
                || op.c_target != NO_BIT
                || op.c_condition != NO_BIT
                || op.r_target != NO_REG
                || op.kind == OperationType::Neg
                || op.kind == OperationType::PopCondition
        }));
        println!("loan_aware_forward_report={report:?}");
    }

    #[test]
    #[ignore = "full loan-aware inverse/replay target report"]
    fn loan_aware_complete_inverse_report() {
        let mut b = B::new();
        let y = b.alloc_qubits(WIDTH);
        let x = b.alloc_qubits(WIDTH);
        let report = emit_inactive_binary_gcd_inverse_in_place(&mut b, &x, &y).unwrap();
        assert_eq!(report.counts.ccx, 3_976_549);
        assert_eq!(report.peak_qubits, 1_627);
        assert_eq!(b.active_qubits, 512);
        assert!(b.ops.iter().all(|op| {
            op.validate();
            op.q_target != NO_QUBIT
                || op.q_control1 != NO_QUBIT
                || op.q_control2 != NO_QUBIT
                || op.c_target != NO_BIT
                || op.c_condition != NO_BIT
                || op.r_target != NO_REG
                || op.kind == OperationType::Neg
                || op.kind == OperationType::PopCondition
        }));
        println!("loan_aware_inverse_report={report:?}");
    }

    #[test]
    #[ignore = "full explicit inverse-orientation target receipt"]
    fn complete_inverse_target_binding_is_frozen() {
        let mut b = B::new();
        let y = b.alloc_qubits(WIDTH);
        let x = b.alloc_qubits(WIDTH);
        let report = emit_inactive_binary_gcd_inverse_in_place(&mut b, &x, &y).unwrap();
        assert_eq!(report.lifecycle_operations, 29_492_818);
        assert_eq!(report.lifecycle_fnv1a128, EXPECTED_INVERSE_LIFECYCLE_FNV1A128);
        assert_eq!(report.measurement_bits, 1_501_699);
        assert_eq!(report.peak_qubits, 1_627);
        assert_eq!(report.total_qubit_ids, 1_627);
        assert_eq!(report.target_operations, 28_897_708);
        assert_eq!(
            report.target_operation_sha3_256,
            "1b672e6cff4740e34f37954fad488e946495618031ae1aecd8cce4bb8b7e17dd"
        );
        assert_eq!(report.counts.x, 7_451_327);
        assert_eq!(report.counts.cx, 11_517_406);
        assert_eq!(report.counts.ccx, 3_976_549);
        assert_eq!(report.counts.swap, 326_912);
        assert_eq!(report.counts.z, 1_039_374);
        assert_eq!(report.counts.cz, 982_012);
        assert_eq!(report.counts.hmr, 1_501_699);
        assert_eq!(report.counts.reset_z, 1_507_831);
        assert_eq!(report.counts.release_r, 594_598);
        assert_eq!(b.active_qubits, 512);
        assert_eq!(b.next_bit, 1_501_699);
        assert!(b.ops.iter().all(|op| {
            op.validate();
            op.q_target != NO_QUBIT
                || op.q_control1 != NO_QUBIT
                || op.q_control2 != NO_QUBIT
                || op.c_target != NO_BIT
                || op.c_condition != NO_BIT
                || op.r_target != NO_REG
                || op.kind == OperationType::Neg
                || op.kind == OperationType::PopCondition
        }));
        println!("inverse_report={report:?}");
    }
}
