//! Literal exact fold prototypes; public ecdsa.fail, no real-world key target.
use super::*;
use crate::circuit::{OperationType as K,NO_BIT};
use sha3::{Shake256,digest::{Update,ExtendableOutput,XofReader}};
include!("fold_tables.rs");
pub(crate) fn try_fold(c:&mut Builder,map:&[Vec<QubitId>],b:&[QubitId],cin:QubitId,room:usize)->bool {
 let mut syms=Vec::new();for &q in map.iter().flatten().chain(std::iter::once(&cin)){if !syms.contains(&q){syms.push(q);}}
 let rows=map.iter().map(|r|r.iter().map(|q|syms.iter().position(|s|s==q).unwrap()).collect::<Vec<_>>()).collect::<Vec<_>>();
 let ci=syms.iter().position(|s|*s==cin).unwrap();let Some(bytes)=table(&rows,ci,room)else{return false};
 let base=c.active_qubits();let at=c.op_count();let bindings=vec![b.to_vec(),syms,vec![]];let(_,t,peak)=emit_bound(c,bytes,Some(&bindings));assert_eq!(c.active_qubits(),base);
 eprintln!("FOLD_PACKED\t{at}\t{}\t{room}\t{t}\t{}",b.len(),peak-bindings.iter().map(Vec::len).sum::<usize>()as u32);true
}
fn num(b:&[u8],p:&mut usize)->u32{let v=u32::from_le_bytes(b[*p..*p+4].try_into().unwrap());*p+=4;v}
fn emit(c:&mut Builder,bytes:&[u8])->(Vec<Vec<QubitId>>,f64,u32){emit_bound(c,bytes,None)}
pub(crate) fn emit_bound(c:&mut Builder,bytes:&[u8],bindings:Option<&[Vec<QubitId>]>)->(Vec<Vec<QubitId>>,f64,u32){assert_eq!(&bytes[..8],b"FOLDBIN1");let mut p=8;let _n=num(bytes,&mut p);let _ns=num(bytes,&mut p);let nq=num(bytes,&mut p)as usize;let nm=num(bytes,&mut p)as usize;let no=num(bytes,&mut p);let t2=u64::from_le_bytes(bytes[p..p+8].try_into().unwrap());p+=8;let peak=num(bytes,&mut p);let mut regs=Vec::new();let mut old=Vec::new();for _ in 0..3{let n=num(bytes,&mut p)as usize;old.push((0..n).map(|_|num(bytes,&mut p)as usize).collect::<Vec<_>>());regs.push(if let Some(bs)=bindings{let r=bs[regs.len()].clone();assert_eq!(r.len(),n);r}else{c.alloc_qubits(n)});}
 let mut qs=vec![None;nq];let mut ext=vec![false;nq];let mut seen=vec![false;nq];let mut ms=vec![None;nm];for(a,b)in old.iter().zip(&regs){for(&i,&q)in a.iter().zip(b){qs[i]=Some(q);ext[i]=true;}}
 for _ in 0..no{let k=bytes[p];p+=1;let a=num(bytes,&mut p)as i32;let b=num(bytes,&mut p)as i32;let d=num(bytes,&mut p)as i32;match k{0=>{let i=a as usize;if !seen[i]&&ext[i]{}else{assert!(qs[i].is_none());qs[i]=Some(c.alloc_qubit());}seen[i]=true;},1=>c.free(qs[a as usize].take().unwrap()),2=>c.x(qs[a as usize].unwrap()),3=>c.cx(qs[a as usize].unwrap(),qs[b as usize].unwrap()),4=>c.ccx(qs[a as usize].unwrap(),qs[b as usize].unwrap(),qs[d as usize].unwrap()),5=>{let m=c.alloc_bit();assert!(ms[b as usize].is_none());ms[b as usize]=Some(m);c.hmr(qs[a as usize].unwrap(),m);},6=>c.z_if(qs[b as usize].unwrap(),ms[a as usize].unwrap()),7=>c.cz_if(qs[b as usize].unwrap(),qs[d as usize].unwrap(),ms[a as usize].unwrap()),8=>c.push_condition(ms[a as usize].unwrap()),9=>c.pop_condition(),_=>panic!("bad template")}}
 for m in ms{c.free_bit(m.unwrap());}assert_eq!(p,bytes.len());(regs,t2 as f64/2.,peak)
}
fn put(q:&mut[u64],r:&[QubitId],v:u128,l:usize){for(j,w)in r.iter().enumerate(){if v>>j&1!=0{q[w.0 as usize]|=1<<l;}}}
fn get(q:&[u64],r:&[QubitId],l:usize)->u128{r.iter().enumerate().fold(0,|v,(j,w)|v|((q[w.0 as usize]>>l&1)as u128)<<j)}
fn apply<R:XofReader>(sim:&mut crate::sim::Simulator<R>,ops:&[Op])->u64{let mut stack=Vec::new();let mut base=u64::MAX;let mut dirty=0;for o in ops{let mut co=base;if o.c_condition!=NO_BIT{co&=sim.bits[o.c_condition.0 as usize];}let t=o.q_target.0 as usize;let a=o.q_control1.0 as usize;let b=o.q_control2.0 as usize;let m=o.c_target.0 as usize;match o.kind{K::X=>sim.qubits[t]^=co,K::CX=>sim.qubits[t]^=co&sim.qubits[a],K::CCX=>sim.qubits[t]^=co&sim.qubits[a]&sim.qubits[b],K::Z=>sim.phase^=co&sim.qubits[t],K::CZ=>sim.phase^=co&sim.qubits[t]&sim.qubits[a],K::CCZ=>sim.phase^=co&sim.qubits[t]&sim.qubits[a]&sim.qubits[b],K::Neg=>sim.phase^=co,K::Hmr|K::R=>{let mut raw=[0;8];sim.xof.read(&mut raw);let v=u64::from_le_bytes(raw);if o.kind==K::R{dirty|=co&sim.qubits[t];}else{sim.bits[m]=(sim.bits[m]&!co)|(v&co);}sim.phase^=co&v&sim.qubits[t];sim.qubits[t]&=!co;},K::PushCondition=>{stack.push(base);base&=sim.bits[o.c_condition.0 as usize];},K::PopCondition=>base=stack.pop().unwrap(),K::Register|K::AppendToRegister|K::DebugPrint=>{},_=>panic!("unexpected native op")}}assert!(stack.is_empty());dirty}
pub fn run(){let dir=std::path::PathBuf::from(std::env::var("FOLD_TEMPLATE_DIR").unwrap());for tag in std::fs::read_to_string(dir.join("templates.txt")).unwrap().lines(){let bytes=std::fs::read(dir.join(format!("{tag}.bin"))).unwrap();let mut c=Builder::new();let(regs,t,peak)=emit(&mut c,&bytes);assert_eq!(c.report_totals().unwrap().1,t);assert_eq!(c.peak_total(),peak);assert_eq!(c.active_qubits()as usize,regs.iter().map(Vec::len).sum::<usize>());let(nq,nb)=c.i13_dims();let ops=c.take_ops();let cases=std::fs::read_to_string(dir.join(format!("{tag}.cases"))).unwrap().lines().map(|l|l.split_whitespace().map(|x|x.parse::<u128>().unwrap()).collect::<Vec<_>>()).collect::<Vec<_>>();
 for(rep,rows)in cases.chunks(64).enumerate(){let mut h=Shake256::default();h.update(tag.as_bytes());h.update(&(rep as u64).to_le_bytes());let mut xr=h.finalize_xof();let mut sim=crate::sim::Simulator::new(nq,nb,&mut xr);for(l,r)in rows.iter().enumerate(){for j in 0..3{put(&mut sim.qubits,&regs[j],r[j],l);}}let dirty=apply(&mut sim,&ops);let mask=if rows.len()==64{u64::MAX}else{(1<<rows.len())-1};assert_eq!(dirty&mask,0,"dirty release {tag}");assert_eq!(sim.phase&mask,0,"phase {tag}");for(l,r)in rows.iter().enumerate(){assert_eq!(get(&sim.qubits,&regs[0],l),r[3],"value {tag}");for j in 1..3{assert_eq!(get(&sim.qubits,&regs[j],l),r[j],"source {tag}");}}for r in &regs{for q in r{sim.qubits[q.0 as usize]=0;}}assert_eq!(sim.qubits.iter().fold(0,|a,b|a|b)&mask,0);}
 let rr=regs.iter().map(|r|r.iter().map(|q|q.0).collect::<Vec<_>>()).collect::<Vec<_>>();let data=ops.iter().map(|o|format!("[{},{},{},{},{},{}]",o.kind as u8,o.q_target.0,o.q_control1.0,o.q_control2.0,o.c_target.0,o.c_condition.0)).collect::<Vec<_>>().join(",");std::fs::write(dir.join(format!("{tag}.native.json")),format!("{{\"nq\":{nq},\"regs\":{{\"b\":{:?},\"s\":{:?},\"dirty\":{:?}}},\"ops\":[{data}]}}",rr[0],rr[1],rr[2])).unwrap();println!("{{\"tag\":\"{tag}\",\"T\":{t},\"Q\":{peak},\"cases\":{},\"literal_ops\":{},\"native_value_phase_cleanup_pass\":true}}",cases.len(),ops.len());}}
