// Generated from formal/ir/frontier-k2-five-row-universal-codec-v1.json.
// Generated Rust is output-only.
// ir_sha256=491cd2d140259126887debce30b261dc216548d1d56b6a95bed9d8261d760962
// generator_sha256=4606cf19a08073c150eccd3d9c2b97288b36decbcb45cd2464f3bbc947400f12

use super::B;
use crate::circuit::QubitId;

pub(super) fn emit_frontier_k2_five_row_encode(circuit: &mut B, w: &[QubitId; 15], scratch: &[QubitId; 13]) {
    circuit.cx(w[4], w[3]);
    circuit.cx(w[3], w[4]);
    circuit.cx(w[3], w[1]);
    circuit.cx(w[3], w[0]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[3], w[2]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[0], w[2]);
    circuit.x(w[0]);
    circuit.x(w[1]);
    circuit.ccx(w[0], w[1], w[2]);
    circuit.x(w[1]);
    circuit.x(w[0]);
    circuit.cx(w[0], w[2]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[3], w[2]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[3], w[0]);
    circuit.cx(w[3], w[1]);
    circuit.cx(w[3], w[4]);
    circuit.cx(w[4], w[3]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[3], w[2]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[1], w[4]);
    circuit.cx(w[1], w[3]);
    circuit.cx(w[1], w[2]);
    circuit.cx(w[2], w[1]);
    circuit.cx(w[1], w[2]);
    circuit.cx(w[0], w[3]);
    circuit.cx(w[3], w[0]);
    circuit.cx(w[0], w[3]);
    circuit.ccx(w[0], w[1], w[2]);
    circuit.cx(w[0], w[3]);
    circuit.cx(w[3], w[0]);
    circuit.cx(w[0], w[3]);
    circuit.cx(w[1], w[2]);
    circuit.cx(w[2], w[1]);
    circuit.cx(w[1], w[2]);
    circuit.cx(w[1], w[3]);
    circuit.cx(w[1], w[4]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[3], w[2]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[3], w[0]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[3], w[2]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[1], w[3]);
    circuit.cx(w[3], w[1]);
    circuit.cx(w[1], w[3]);
    circuit.cx(w[0], w[2]);
    circuit.cx(w[0], w[1]);
    circuit.cx(w[1], w[0]);
    circuit.cx(w[0], w[1]);
    circuit.ccx(w[0], w[1], w[2]);
    circuit.cx(w[0], w[1]);
    circuit.cx(w[1], w[0]);
    circuit.cx(w[0], w[1]);
    circuit.cx(w[0], w[2]);
    circuit.cx(w[1], w[3]);
    circuit.cx(w[3], w[1]);
    circuit.cx(w[1], w[3]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[3], w[2]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[3], w[0]);
    circuit.x(w[3]);
    circuit.x(w[5]);
    circuit.cx(w[7], w[6]);
    circuit.x(w[6]);
    circuit.ccx(w[5], w[6], w[7]);
    circuit.x(w[6]);
    circuit.x(w[8]);
    circuit.cx(w[10], w[9]);
    circuit.x(w[9]);
    circuit.ccx(w[8], w[9], w[10]);
    circuit.x(w[9]);
    circuit.x(w[11]);
    circuit.cx(w[13], w[12]);
    circuit.x(w[12]);
    circuit.ccx(w[11], w[12], w[13]);
    circuit.x(w[12]);
    circuit.cx(w[8], scratch[0]);
    circuit.cx(w[9], scratch[1]);
    circuit.cx(w[10], scratch[2]);
    circuit.x(scratch[3]);
    circuit.x(scratch[4]);
    circuit.ccx(scratch[0], scratch[11], w[5]);
    circuit.ccx(scratch[0], scratch[3], scratch[11]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[0], scratch[3], w[6]);
    circuit.ccx(scratch[0], scratch[4], scratch[3]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[0], scratch[4], w[7]);
    circuit.ccx(scratch[0], scratch[5], scratch[4]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[0], scratch[5], w[8]);
    circuit.ccx(scratch[0], scratch[6], scratch[5]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[0], scratch[6], w[9]);
    circuit.ccx(scratch[0], scratch[7], scratch[6]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[0], scratch[8], w[10]);
    circuit.ccx(scratch[0], scratch[7], w[10]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[0], scratch[7], scratch[6]);
    circuit.ccx(scratch[0], scratch[7], w[9]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[0], scratch[6], scratch[5]);
    circuit.ccx(scratch[0], scratch[6], w[8]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[0], scratch[5], scratch[4]);
    circuit.ccx(scratch[0], scratch[5], w[7]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[0], scratch[4], scratch[3]);
    circuit.ccx(scratch[0], scratch[4], w[6]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[0], scratch[3], scratch[11]);
    circuit.ccx(scratch[0], scratch[3], w[5]);
    circuit.x(scratch[4]);
    circuit.x(scratch[3]);
    circuit.x(scratch[4]);
    circuit.x(scratch[5]);
    circuit.ccx(scratch[1], scratch[11], w[5]);
    circuit.ccx(scratch[1], scratch[3], scratch[11]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[1], scratch[3], w[6]);
    circuit.ccx(scratch[1], scratch[4], scratch[3]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[1], scratch[4], w[7]);
    circuit.ccx(scratch[1], scratch[5], scratch[4]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[1], scratch[5], w[8]);
    circuit.ccx(scratch[1], scratch[6], scratch[5]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[1], scratch[6], w[9]);
    circuit.ccx(scratch[1], scratch[7], scratch[6]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[1], scratch[8], w[10]);
    circuit.ccx(scratch[1], scratch[7], w[10]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[1], scratch[7], scratch[6]);
    circuit.ccx(scratch[1], scratch[7], w[9]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[1], scratch[6], scratch[5]);
    circuit.ccx(scratch[1], scratch[6], w[8]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[1], scratch[5], scratch[4]);
    circuit.ccx(scratch[1], scratch[5], w[7]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[1], scratch[4], scratch[3]);
    circuit.ccx(scratch[1], scratch[4], w[6]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[1], scratch[3], scratch[11]);
    circuit.ccx(scratch[1], scratch[3], w[5]);
    circuit.x(scratch[5]);
    circuit.x(scratch[4]);
    circuit.x(scratch[5]);
    circuit.x(scratch[6]);
    circuit.ccx(scratch[2], scratch[11], w[5]);
    circuit.ccx(scratch[2], scratch[3], scratch[11]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[2], scratch[3], w[6]);
    circuit.ccx(scratch[2], scratch[4], scratch[3]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[2], scratch[4], w[7]);
    circuit.ccx(scratch[2], scratch[5], scratch[4]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[2], scratch[5], w[8]);
    circuit.ccx(scratch[2], scratch[6], scratch[5]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[2], scratch[6], w[9]);
    circuit.ccx(scratch[2], scratch[7], scratch[6]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[2], scratch[8], w[10]);
    circuit.ccx(scratch[2], scratch[7], w[10]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[2], scratch[7], scratch[6]);
    circuit.ccx(scratch[2], scratch[7], w[9]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[2], scratch[6], scratch[5]);
    circuit.ccx(scratch[2], scratch[6], w[8]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[2], scratch[5], scratch[4]);
    circuit.ccx(scratch[2], scratch[5], w[7]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[2], scratch[4], scratch[3]);
    circuit.ccx(scratch[2], scratch[4], w[6]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[2], scratch[3], scratch[11]);
    circuit.ccx(scratch[2], scratch[3], w[5]);
    circuit.x(scratch[6]);
    circuit.x(scratch[5]);
    circuit.ccx(w[5], w[7], scratch[0]);
    circuit.ccx(w[6], w[7], scratch[0]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[7], scratch[0]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.cx(w[8], scratch[0]);
    circuit.ccx(w[6], w[8], scratch[0]);
    circuit.ccx(w[7], w[8], scratch[0]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[0]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.cx(w[9], scratch[0]);
    circuit.ccx(w[7], w[9], scratch[0]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[0]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[0]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[0]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[6], w[8], scratch[1]);
    circuit.ccx(w[7], w[8], scratch[1]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[1]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.cx(w[9], scratch[1]);
    circuit.ccx(w[7], w[9], scratch[1]);
    circuit.ccx(w[8], w[9], scratch[1]);
    circuit.ccx(w[7], w[9], scratch[2]);
    circuit.ccx(w[8], w[9], scratch[2]);
    circuit.cx(w[11], scratch[0]);
    circuit.cx(w[12], scratch[1]);
    circuit.cx(w[13], scratch[2]);
    circuit.x(scratch[3]);
    circuit.x(scratch[4]);
    circuit.x(scratch[5]);
    circuit.ccx(scratch[0], scratch[11], w[5]);
    circuit.ccx(scratch[0], scratch[3], scratch[11]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[0], scratch[3], w[6]);
    circuit.ccx(scratch[0], scratch[4], scratch[3]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[0], scratch[4], w[7]);
    circuit.ccx(scratch[0], scratch[5], scratch[4]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[0], scratch[5], w[8]);
    circuit.ccx(scratch[0], scratch[6], scratch[5]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[0], scratch[6], w[9]);
    circuit.ccx(scratch[0], scratch[7], scratch[6]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[0], scratch[7], w[11]);
    circuit.ccx(scratch[0], scratch[8], scratch[7]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[8]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[0], scratch[8], w[12]);
    circuit.ccx(scratch[0], scratch[9], scratch[8]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[9]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[0], scratch[10], w[13]);
    circuit.ccx(scratch[0], scratch[9], w[13]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[9]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[0], scratch[9], scratch[8]);
    circuit.ccx(scratch[0], scratch[9], w[12]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[8]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[0], scratch[8], scratch[7]);
    circuit.ccx(scratch[0], scratch[8], w[11]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[0], scratch[7], scratch[6]);
    circuit.ccx(scratch[0], scratch[7], w[9]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[0], scratch[6], scratch[5]);
    circuit.ccx(scratch[0], scratch[6], w[8]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[0], scratch[5], scratch[4]);
    circuit.ccx(scratch[0], scratch[5], w[7]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[0], scratch[4], scratch[3]);
    circuit.ccx(scratch[0], scratch[4], w[6]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[0], scratch[3], scratch[11]);
    circuit.ccx(scratch[0], scratch[3], w[5]);
    circuit.x(scratch[5]);
    circuit.x(scratch[4]);
    circuit.x(scratch[3]);
    circuit.x(scratch[4]);
    circuit.x(scratch[5]);
    circuit.x(scratch[6]);
    circuit.ccx(scratch[1], scratch[11], w[5]);
    circuit.ccx(scratch[1], scratch[3], scratch[11]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[1], scratch[3], w[6]);
    circuit.ccx(scratch[1], scratch[4], scratch[3]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[1], scratch[4], w[7]);
    circuit.ccx(scratch[1], scratch[5], scratch[4]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[1], scratch[5], w[8]);
    circuit.ccx(scratch[1], scratch[6], scratch[5]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[1], scratch[6], w[9]);
    circuit.ccx(scratch[1], scratch[7], scratch[6]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[1], scratch[7], w[11]);
    circuit.ccx(scratch[1], scratch[8], scratch[7]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[8]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[1], scratch[8], w[12]);
    circuit.ccx(scratch[1], scratch[9], scratch[8]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[9]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[1], scratch[10], w[13]);
    circuit.ccx(scratch[1], scratch[9], w[13]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[9]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[1], scratch[9], scratch[8]);
    circuit.ccx(scratch[1], scratch[9], w[12]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[8]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[1], scratch[8], scratch[7]);
    circuit.ccx(scratch[1], scratch[8], w[11]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[1], scratch[7], scratch[6]);
    circuit.ccx(scratch[1], scratch[7], w[9]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[1], scratch[6], scratch[5]);
    circuit.ccx(scratch[1], scratch[6], w[8]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[1], scratch[5], scratch[4]);
    circuit.ccx(scratch[1], scratch[5], w[7]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[1], scratch[4], scratch[3]);
    circuit.ccx(scratch[1], scratch[4], w[6]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[1], scratch[3], scratch[11]);
    circuit.ccx(scratch[1], scratch[3], w[5]);
    circuit.x(scratch[6]);
    circuit.x(scratch[5]);
    circuit.x(scratch[4]);
    circuit.x(scratch[5]);
    circuit.x(scratch[6]);
    circuit.x(scratch[7]);
    circuit.ccx(scratch[2], scratch[11], w[5]);
    circuit.ccx(scratch[2], scratch[3], scratch[11]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[2], scratch[3], w[6]);
    circuit.ccx(scratch[2], scratch[4], scratch[3]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[2], scratch[4], w[7]);
    circuit.ccx(scratch[2], scratch[5], scratch[4]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[2], scratch[5], w[8]);
    circuit.ccx(scratch[2], scratch[6], scratch[5]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[2], scratch[6], w[9]);
    circuit.ccx(scratch[2], scratch[7], scratch[6]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[2], scratch[7], w[11]);
    circuit.ccx(scratch[2], scratch[8], scratch[7]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[8]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[2], scratch[8], w[12]);
    circuit.ccx(scratch[2], scratch[9], scratch[8]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[9]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[2], scratch[10], w[13]);
    circuit.ccx(scratch[2], scratch[9], w[13]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[9]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[2], scratch[9], scratch[8]);
    circuit.ccx(scratch[2], scratch[9], w[12]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[8]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[2], scratch[8], scratch[7]);
    circuit.ccx(scratch[2], scratch[8], w[11]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[2], scratch[7], scratch[6]);
    circuit.ccx(scratch[2], scratch[7], w[9]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[2], scratch[6], scratch[5]);
    circuit.ccx(scratch[2], scratch[6], w[8]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[2], scratch[5], scratch[4]);
    circuit.ccx(scratch[2], scratch[5], w[7]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[2], scratch[4], scratch[3]);
    circuit.ccx(scratch[2], scratch[4], w[6]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[2], scratch[3], scratch[11]);
    circuit.ccx(scratch[2], scratch[3], w[5]);
    circuit.x(scratch[7]);
    circuit.x(scratch[6]);
    circuit.x(scratch[5]);
    circuit.ccx(w[5], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[0]);
    circuit.ccx(w[5], w[8], scratch[3]);
    circuit.ccx(w[6], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[0]);
    circuit.ccx(w[6], w[8], scratch[3]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[0]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[0]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[0]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[0]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(scratch[4], w[8], scratch[5]);
    circuit.ccx(scratch[5], w[9], scratch[0]);
    circuit.ccx(scratch[4], w[8], scratch[5]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.cx(w[11], scratch[0]);
    circuit.ccx(w[6], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[0]);
    circuit.ccx(w[6], w[9], scratch[3]);
    circuit.ccx(w[7], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[0]);
    circuit.ccx(w[7], w[9], scratch[3]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[0]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(w[8], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[0]);
    circuit.ccx(w[8], w[9], scratch[3]);
    circuit.ccx(w[5], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[0]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[5], w[8], scratch[3]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[5], w[11], scratch[0]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[5], w[11], scratch[0]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(scratch[4], w[8], scratch[5]);
    circuit.ccx(scratch[5], w[9], scratch[6]);
    circuit.ccx(scratch[6], w[11], scratch[0]);
    circuit.ccx(scratch[5], w[9], scratch[6]);
    circuit.ccx(scratch[4], w[8], scratch[5]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[0]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[0]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(scratch[4], w[8], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[0]);
    circuit.ccx(scratch[4], w[8], scratch[5]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[9], w[12], scratch[0]);
    circuit.ccx(w[5], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[0]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[5], w[8], scratch[3]);
    circuit.ccx(w[6], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[0]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[6], w[8], scratch[3]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[0]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[0]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(w[7], w[11], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[0]);
    circuit.ccx(w[7], w[11], scratch[3]);
    circuit.ccx(w[8], w[11], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[0]);
    circuit.ccx(w[8], w[11], scratch[3]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[0]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(scratch[4], w[8], scratch[5]);
    circuit.ccx(scratch[5], w[11], scratch[6]);
    circuit.ccx(scratch[6], w[12], scratch[0]);
    circuit.ccx(scratch[5], w[11], scratch[6]);
    circuit.ccx(scratch[4], w[8], scratch[5]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[6], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[0]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(w[6], w[9], scratch[3]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[0]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(w[5], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[0]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[5], w[8], scratch[3]);
    circuit.ccx(w[6], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[1]);
    circuit.ccx(w[6], w[9], scratch[3]);
    circuit.ccx(w[7], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[1]);
    circuit.ccx(w[7], w[9], scratch[3]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[1]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(w[8], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[1]);
    circuit.ccx(w[8], w[9], scratch[3]);
    circuit.ccx(w[6], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[1]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[6], w[8], scratch[3]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[1]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[5], w[11], scratch[1]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.cx(w[12], scratch[1]);
    circuit.ccx(w[7], w[11], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[1]);
    circuit.ccx(w[7], w[11], scratch[3]);
    circuit.ccx(w[8], w[11], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[1]);
    circuit.ccx(w[8], w[11], scratch[3]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[1]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(w[9], w[11], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[1]);
    circuit.ccx(w[9], w[11], scratch[3]);
    circuit.ccx(w[6], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[1]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(w[6], w[9], scratch[3]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[1]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(w[6], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[1]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[6], w[8], scratch[3]);
    circuit.ccx(w[7], w[11], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[2]);
    circuit.ccx(w[7], w[11], scratch[3]);
    circuit.ccx(w[8], w[11], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[2]);
    circuit.ccx(w[8], w[11], scratch[3]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[2]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(w[9], w[11], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[2]);
    circuit.ccx(w[9], w[11], scratch[3]);
    circuit.ccx(w[7], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[2]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(w[7], w[9], scratch[3]);
    circuit.ccx(w[8], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[2]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(w[8], w[9], scratch[3]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[2]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[7], w[8], scratch[3]);
}

pub(super) fn emit_frontier_k2_five_row_decode(circuit: &mut B, w: &[QubitId; 15], scratch: &[QubitId; 13]) {
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[2]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(w[8], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[2]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(w[8], w[9], scratch[3]);
    circuit.ccx(w[7], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[2]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(w[7], w[9], scratch[3]);
    circuit.ccx(w[9], w[11], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[2]);
    circuit.ccx(w[9], w[11], scratch[3]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[2]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(w[8], w[11], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[2]);
    circuit.ccx(w[8], w[11], scratch[3]);
    circuit.ccx(w[7], w[11], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[2]);
    circuit.ccx(w[7], w[11], scratch[3]);
    circuit.ccx(w[6], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[1]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[6], w[8], scratch[3]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[1]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(w[6], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[1]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(w[6], w[9], scratch[3]);
    circuit.ccx(w[9], w[11], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[1]);
    circuit.ccx(w[9], w[11], scratch[3]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[1]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(w[8], w[11], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[1]);
    circuit.ccx(w[8], w[11], scratch[3]);
    circuit.ccx(w[7], w[11], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[1]);
    circuit.ccx(w[7], w[11], scratch[3]);
    circuit.cx(w[12], scratch[1]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[5], w[11], scratch[1]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[1]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(w[6], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[1]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[6], w[8], scratch[3]);
    circuit.ccx(w[8], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[1]);
    circuit.ccx(w[8], w[9], scratch[3]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[1]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(w[7], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[1]);
    circuit.ccx(w[7], w[9], scratch[3]);
    circuit.ccx(w[6], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[1]);
    circuit.ccx(w[6], w[9], scratch[3]);
    circuit.ccx(w[5], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[0]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[5], w[8], scratch[3]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[0]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(w[6], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[0]);
    circuit.ccx(scratch[3], w[11], scratch[4]);
    circuit.ccx(w[6], w[9], scratch[3]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(scratch[4], w[8], scratch[5]);
    circuit.ccx(scratch[5], w[11], scratch[6]);
    circuit.ccx(scratch[6], w[12], scratch[0]);
    circuit.ccx(scratch[5], w[11], scratch[6]);
    circuit.ccx(scratch[4], w[8], scratch[5]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[0]);
    circuit.ccx(scratch[4], w[11], scratch[5]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[8], w[11], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[0]);
    circuit.ccx(w[8], w[11], scratch[3]);
    circuit.ccx(w[7], w[11], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[0]);
    circuit.ccx(w[7], w[11], scratch[3]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[0]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[0]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(w[6], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[0]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[6], w[8], scratch[3]);
    circuit.ccx(w[5], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[0]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[5], w[8], scratch[3]);
    circuit.ccx(w[9], w[12], scratch[0]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(scratch[4], w[8], scratch[5]);
    circuit.ccx(scratch[5], w[12], scratch[0]);
    circuit.ccx(scratch[4], w[8], scratch[5]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[12], scratch[0]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[12], scratch[0]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(scratch[4], w[8], scratch[5]);
    circuit.ccx(scratch[5], w[9], scratch[6]);
    circuit.ccx(scratch[6], w[11], scratch[0]);
    circuit.ccx(scratch[5], w[9], scratch[6]);
    circuit.ccx(scratch[4], w[8], scratch[5]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[5], w[11], scratch[0]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[5], w[11], scratch[0]);
    circuit.ccx(scratch[4], w[9], scratch[5]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[5], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[0]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[5], w[8], scratch[3]);
    circuit.ccx(w[8], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[0]);
    circuit.ccx(w[8], w[9], scratch[3]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(scratch[4], w[11], scratch[0]);
    circuit.ccx(scratch[3], w[9], scratch[4]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(w[7], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[0]);
    circuit.ccx(w[7], w[9], scratch[3]);
    circuit.ccx(w[6], w[9], scratch[3]);
    circuit.ccx(scratch[3], w[11], scratch[0]);
    circuit.ccx(w[6], w[9], scratch[3]);
    circuit.cx(w[11], scratch[0]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(scratch[4], w[8], scratch[5]);
    circuit.ccx(scratch[5], w[9], scratch[0]);
    circuit.ccx(scratch[4], w[8], scratch[5]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[0]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[0]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[0]);
    circuit.ccx(w[7], w[8], scratch[3]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[0]);
    circuit.ccx(scratch[3], w[8], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[6], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[0]);
    circuit.ccx(w[6], w[8], scratch[3]);
    circuit.ccx(w[5], w[8], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[0]);
    circuit.ccx(w[5], w[8], scratch[3]);
    circuit.x(scratch[5]);
    circuit.x(scratch[6]);
    circuit.x(scratch[7]);
    circuit.ccx(scratch[2], scratch[3], w[5]);
    circuit.ccx(scratch[2], scratch[3], scratch[11]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[2], scratch[4], w[6]);
    circuit.ccx(scratch[2], scratch[4], scratch[3]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[2], scratch[5], w[7]);
    circuit.ccx(scratch[2], scratch[5], scratch[4]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[2], scratch[6], w[8]);
    circuit.ccx(scratch[2], scratch[6], scratch[5]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[2], scratch[7], w[9]);
    circuit.ccx(scratch[2], scratch[7], scratch[6]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[2], scratch[8], w[11]);
    circuit.ccx(scratch[2], scratch[8], scratch[7]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[8]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[2], scratch[9], w[12]);
    circuit.ccx(scratch[2], scratch[9], scratch[8]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[9]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[2], scratch[9], w[13]);
    circuit.ccx(scratch[2], scratch[10], w[13]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[9]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[2], scratch[9], scratch[8]);
    circuit.ccx(scratch[2], scratch[8], w[12]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[8]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[2], scratch[8], scratch[7]);
    circuit.ccx(scratch[2], scratch[7], w[11]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[2], scratch[7], scratch[6]);
    circuit.ccx(scratch[2], scratch[6], w[9]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[2], scratch[6], scratch[5]);
    circuit.ccx(scratch[2], scratch[5], w[8]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[2], scratch[5], scratch[4]);
    circuit.ccx(scratch[2], scratch[4], w[7]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[2], scratch[4], scratch[3]);
    circuit.ccx(scratch[2], scratch[3], w[6]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[2], scratch[3], scratch[11]);
    circuit.ccx(scratch[2], scratch[11], w[5]);
    circuit.x(scratch[7]);
    circuit.x(scratch[6]);
    circuit.x(scratch[5]);
    circuit.x(scratch[4]);
    circuit.x(scratch[5]);
    circuit.x(scratch[6]);
    circuit.ccx(scratch[1], scratch[3], w[5]);
    circuit.ccx(scratch[1], scratch[3], scratch[11]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[1], scratch[4], w[6]);
    circuit.ccx(scratch[1], scratch[4], scratch[3]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[1], scratch[5], w[7]);
    circuit.ccx(scratch[1], scratch[5], scratch[4]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[1], scratch[6], w[8]);
    circuit.ccx(scratch[1], scratch[6], scratch[5]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[1], scratch[7], w[9]);
    circuit.ccx(scratch[1], scratch[7], scratch[6]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[1], scratch[8], w[11]);
    circuit.ccx(scratch[1], scratch[8], scratch[7]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[8]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[1], scratch[9], w[12]);
    circuit.ccx(scratch[1], scratch[9], scratch[8]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[9]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[1], scratch[9], w[13]);
    circuit.ccx(scratch[1], scratch[10], w[13]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[9]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[1], scratch[9], scratch[8]);
    circuit.ccx(scratch[1], scratch[8], w[12]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[8]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[1], scratch[8], scratch[7]);
    circuit.ccx(scratch[1], scratch[7], w[11]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[1], scratch[7], scratch[6]);
    circuit.ccx(scratch[1], scratch[6], w[9]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[1], scratch[6], scratch[5]);
    circuit.ccx(scratch[1], scratch[5], w[8]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[1], scratch[5], scratch[4]);
    circuit.ccx(scratch[1], scratch[4], w[7]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[1], scratch[4], scratch[3]);
    circuit.ccx(scratch[1], scratch[3], w[6]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[1], scratch[3], scratch[11]);
    circuit.ccx(scratch[1], scratch[11], w[5]);
    circuit.x(scratch[6]);
    circuit.x(scratch[5]);
    circuit.x(scratch[4]);
    circuit.x(scratch[3]);
    circuit.x(scratch[4]);
    circuit.x(scratch[5]);
    circuit.ccx(scratch[0], scratch[3], w[5]);
    circuit.ccx(scratch[0], scratch[3], scratch[11]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[0], scratch[4], w[6]);
    circuit.ccx(scratch[0], scratch[4], scratch[3]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[0], scratch[5], w[7]);
    circuit.ccx(scratch[0], scratch[5], scratch[4]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[0], scratch[6], w[8]);
    circuit.ccx(scratch[0], scratch[6], scratch[5]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[0], scratch[7], w[9]);
    circuit.ccx(scratch[0], scratch[7], scratch[6]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[0], scratch[8], w[11]);
    circuit.ccx(scratch[0], scratch[8], scratch[7]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[8]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[0], scratch[9], w[12]);
    circuit.ccx(scratch[0], scratch[9], scratch[8]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[9]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[0], scratch[9], w[13]);
    circuit.ccx(scratch[0], scratch[10], w[13]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[9]);
    circuit.ccx(scratch[8], w[12], scratch[12]);
    circuit.ccx(scratch[0], scratch[9], scratch[8]);
    circuit.ccx(scratch[0], scratch[8], w[12]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[8]);
    circuit.ccx(scratch[7], w[11], scratch[12]);
    circuit.ccx(scratch[0], scratch[8], scratch[7]);
    circuit.ccx(scratch[0], scratch[7], w[11]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[0], scratch[7], scratch[6]);
    circuit.ccx(scratch[0], scratch[6], w[9]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[0], scratch[6], scratch[5]);
    circuit.ccx(scratch[0], scratch[5], w[8]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[0], scratch[5], scratch[4]);
    circuit.ccx(scratch[0], scratch[4], w[7]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[0], scratch[4], scratch[3]);
    circuit.ccx(scratch[0], scratch[3], w[6]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[0], scratch[3], scratch[11]);
    circuit.ccx(scratch[0], scratch[11], w[5]);
    circuit.x(scratch[5]);
    circuit.x(scratch[4]);
    circuit.x(scratch[3]);
    circuit.cx(w[13], scratch[2]);
    circuit.cx(w[12], scratch[1]);
    circuit.cx(w[11], scratch[0]);
    circuit.ccx(w[8], w[9], scratch[2]);
    circuit.ccx(w[7], w[9], scratch[2]);
    circuit.ccx(w[8], w[9], scratch[1]);
    circuit.ccx(w[7], w[9], scratch[1]);
    circuit.cx(w[9], scratch[1]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[1]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(w[7], w[8], scratch[1]);
    circuit.ccx(w[6], w[8], scratch[1]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(scratch[4], w[9], scratch[0]);
    circuit.ccx(scratch[3], w[7], scratch[4]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[0]);
    circuit.ccx(w[6], w[7], scratch[3]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[9], scratch[0]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(w[7], w[9], scratch[0]);
    circuit.cx(w[9], scratch[0]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(scratch[3], w[8], scratch[0]);
    circuit.ccx(w[5], w[7], scratch[3]);
    circuit.ccx(w[7], w[8], scratch[0]);
    circuit.ccx(w[6], w[8], scratch[0]);
    circuit.cx(w[8], scratch[0]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(scratch[3], w[7], scratch[0]);
    circuit.ccx(w[5], w[6], scratch[3]);
    circuit.ccx(w[6], w[7], scratch[0]);
    circuit.ccx(w[5], w[7], scratch[0]);
    circuit.x(scratch[5]);
    circuit.x(scratch[6]);
    circuit.ccx(scratch[2], scratch[3], w[5]);
    circuit.ccx(scratch[2], scratch[3], scratch[11]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[2], scratch[4], w[6]);
    circuit.ccx(scratch[2], scratch[4], scratch[3]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[2], scratch[5], w[7]);
    circuit.ccx(scratch[2], scratch[5], scratch[4]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[2], scratch[6], w[8]);
    circuit.ccx(scratch[2], scratch[6], scratch[5]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[2], scratch[7], w[9]);
    circuit.ccx(scratch[2], scratch[7], scratch[6]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[2], scratch[7], w[10]);
    circuit.ccx(scratch[2], scratch[8], w[10]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[2], scratch[7], scratch[6]);
    circuit.ccx(scratch[2], scratch[6], w[9]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[2], scratch[6], scratch[5]);
    circuit.ccx(scratch[2], scratch[5], w[8]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[2], scratch[5], scratch[4]);
    circuit.ccx(scratch[2], scratch[4], w[7]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[2], scratch[4], scratch[3]);
    circuit.ccx(scratch[2], scratch[3], w[6]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[2], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[2], scratch[3], scratch[11]);
    circuit.ccx(scratch[2], scratch[11], w[5]);
    circuit.x(scratch[6]);
    circuit.x(scratch[5]);
    circuit.x(scratch[4]);
    circuit.x(scratch[5]);
    circuit.ccx(scratch[1], scratch[3], w[5]);
    circuit.ccx(scratch[1], scratch[3], scratch[11]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[1], scratch[4], w[6]);
    circuit.ccx(scratch[1], scratch[4], scratch[3]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[1], scratch[5], w[7]);
    circuit.ccx(scratch[1], scratch[5], scratch[4]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[1], scratch[6], w[8]);
    circuit.ccx(scratch[1], scratch[6], scratch[5]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[1], scratch[7], w[9]);
    circuit.ccx(scratch[1], scratch[7], scratch[6]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[1], scratch[7], w[10]);
    circuit.ccx(scratch[1], scratch[8], w[10]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[1], scratch[7], scratch[6]);
    circuit.ccx(scratch[1], scratch[6], w[9]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[1], scratch[6], scratch[5]);
    circuit.ccx(scratch[1], scratch[5], w[8]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[1], scratch[5], scratch[4]);
    circuit.ccx(scratch[1], scratch[4], w[7]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[1], scratch[4], scratch[3]);
    circuit.ccx(scratch[1], scratch[3], w[6]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[1], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[1], scratch[3], scratch[11]);
    circuit.ccx(scratch[1], scratch[11], w[5]);
    circuit.x(scratch[5]);
    circuit.x(scratch[4]);
    circuit.x(scratch[3]);
    circuit.x(scratch[4]);
    circuit.ccx(scratch[0], scratch[3], w[5]);
    circuit.ccx(scratch[0], scratch[3], scratch[11]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[0], scratch[4], w[6]);
    circuit.ccx(scratch[0], scratch[4], scratch[3]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[0], scratch[5], w[7]);
    circuit.ccx(scratch[0], scratch[5], scratch[4]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[0], scratch[6], w[8]);
    circuit.ccx(scratch[0], scratch[6], scratch[5]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[0], scratch[7], w[9]);
    circuit.ccx(scratch[0], scratch[7], scratch[6]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[0], scratch[7], w[10]);
    circuit.ccx(scratch[0], scratch[8], w[10]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[7]);
    circuit.ccx(scratch[6], w[9], scratch[12]);
    circuit.ccx(scratch[0], scratch[7], scratch[6]);
    circuit.ccx(scratch[0], scratch[6], w[9]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[6]);
    circuit.ccx(scratch[5], w[8], scratch[12]);
    circuit.ccx(scratch[0], scratch[6], scratch[5]);
    circuit.ccx(scratch[0], scratch[5], w[8]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[5]);
    circuit.ccx(scratch[4], w[7], scratch[12]);
    circuit.ccx(scratch[0], scratch[5], scratch[4]);
    circuit.ccx(scratch[0], scratch[4], w[7]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[4]);
    circuit.ccx(scratch[3], w[6], scratch[12]);
    circuit.ccx(scratch[0], scratch[4], scratch[3]);
    circuit.ccx(scratch[0], scratch[3], w[6]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[0], scratch[12], scratch[3]);
    circuit.ccx(scratch[11], w[5], scratch[12]);
    circuit.ccx(scratch[0], scratch[3], scratch[11]);
    circuit.ccx(scratch[0], scratch[11], w[5]);
    circuit.x(scratch[4]);
    circuit.x(scratch[3]);
    circuit.cx(w[10], scratch[2]);
    circuit.cx(w[9], scratch[1]);
    circuit.cx(w[8], scratch[0]);
    circuit.x(w[12]);
    circuit.ccx(w[11], w[12], w[13]);
    circuit.x(w[12]);
    circuit.cx(w[13], w[12]);
    circuit.x(w[11]);
    circuit.x(w[9]);
    circuit.ccx(w[8], w[9], w[10]);
    circuit.x(w[9]);
    circuit.cx(w[10], w[9]);
    circuit.x(w[8]);
    circuit.x(w[6]);
    circuit.ccx(w[5], w[6], w[7]);
    circuit.x(w[6]);
    circuit.cx(w[7], w[6]);
    circuit.x(w[5]);
    circuit.x(w[3]);
    circuit.cx(w[3], w[0]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[3], w[2]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[1], w[3]);
    circuit.cx(w[3], w[1]);
    circuit.cx(w[1], w[3]);
    circuit.cx(w[0], w[2]);
    circuit.cx(w[0], w[1]);
    circuit.cx(w[1], w[0]);
    circuit.cx(w[0], w[1]);
    circuit.ccx(w[0], w[1], w[2]);
    circuit.cx(w[0], w[1]);
    circuit.cx(w[1], w[0]);
    circuit.cx(w[0], w[1]);
    circuit.cx(w[0], w[2]);
    circuit.cx(w[1], w[3]);
    circuit.cx(w[3], w[1]);
    circuit.cx(w[1], w[3]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[3], w[2]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[3], w[0]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[3], w[2]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[1], w[4]);
    circuit.cx(w[1], w[3]);
    circuit.cx(w[1], w[2]);
    circuit.cx(w[2], w[1]);
    circuit.cx(w[1], w[2]);
    circuit.cx(w[0], w[3]);
    circuit.cx(w[3], w[0]);
    circuit.cx(w[0], w[3]);
    circuit.ccx(w[0], w[1], w[2]);
    circuit.cx(w[0], w[3]);
    circuit.cx(w[3], w[0]);
    circuit.cx(w[0], w[3]);
    circuit.cx(w[1], w[2]);
    circuit.cx(w[2], w[1]);
    circuit.cx(w[1], w[2]);
    circuit.cx(w[1], w[3]);
    circuit.cx(w[1], w[4]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[3], w[2]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[4], w[3]);
    circuit.cx(w[3], w[4]);
    circuit.cx(w[3], w[1]);
    circuit.cx(w[3], w[0]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[3], w[2]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[0], w[2]);
    circuit.x(w[0]);
    circuit.x(w[1]);
    circuit.ccx(w[0], w[1], w[2]);
    circuit.x(w[1]);
    circuit.x(w[0]);
    circuit.cx(w[0], w[2]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[3], w[2]);
    circuit.cx(w[2], w[3]);
    circuit.cx(w[3], w[0]);
    circuit.cx(w[3], w[1]);
    circuit.cx(w[3], w[4]);
    circuit.cx(w[4], w[3]);
}
