// @generated by tools/ecdlp_codegen.py
// generator-version: ecdlp-codegen/v1
// generator-sha256: 9f2e055ad2441049ef63a01ac34341c7fcc8880323d3734b573036cb5d6d8471
// profile-sha256: afc3be6a118b3dead47539821d6e0f4eb7186479b0ffdcead2c95eecc8e91790
// artifact: generated_exact_square.rs
// formal-input: formal/lean/EccFormal/PointAddAlgorithm.lean sha256=e83ac9d653eea9750badc997f47623f38b7713962a792c5a3cca052df6096184 authority=kernel-proved theorems=EccFormal.PointAddAlgorithm.parent_register_composition_refines_affine
// formal-input: formal/lean/EccFormal/BinaryGcdConvergence.lean sha256=628c7ba200df167c9707dfedcf381b9a344bd1b550f4157404dbf46ccda90712 authority=kernel-proved theorems=EccFormal.BinaryGcdConvergence.secp256k1_complete_fixed_511
// formal-input: formal/lean/EccFormal/BinaryGcdGarbageReplay.lean sha256=39b046f88cc76dc84a776c71a66a28b66d11989dbce6c3bb89565e3f4b027542 authority=kernel-proved theorems=EccFormal.BinaryGcdGarbageReplay.inverse_value_walk_restores_complete_trace,EccFormal.BinaryGcdGarbageReplay.coefficient_replay_complete_coprime_orientation,EccFormal.BinaryGcdGarbageReplay.coefficient_replay_complete_coprime_inverse_orientation
// formal-input: formal/lean/EccFormal/BinaryGcdInPlaceMultiplication.lean sha256=2ff4c7e2cb450e8a8c2b1fc668f966bc7a1747a533c5fbd23d3b24b4bc2b0395 authority=kernel-proved theorems=EccFormal.BinaryGcdInPlaceMultiplication.complete_in_place_multiply_relation
// formal-input: formal/lean/EccFormal/BinaryGcdPhysicalRelease.lean sha256=ebd123fb2916831caf2f5dd9a4ae3670071e4bc12c48bf629ecbc72c5bb46668 authority=kernel-proved theorems=EccFormal.BinaryGcdPhysicalRelease.secp256k1_uniform_high_wires_clear,EccFormal.BinaryGcdPhysicalRelease.fixed_replay_peak_with_seven_scratch
// formal-input: formal/lean/EccFormal/BinaryGcdUniformLedger.lean sha256=1032c4b9fd203bd502aa577468a06a2e80200a9a64ae682a90b134eeadfa1ae4 authority=kernel-proved theorems=EccFormal.BinaryGcdUniformLedger.secp256k1_uniform_component_widths,EccFormal.BinaryGcdUniformLedger.forward_persistent_cap
// formal-input: formal/lean/EccFormal/ApproxReplayBadEvents.lean sha256=064f5d305cf9bd94e6e2a56abbf997ad70c1b46bc3c8b68c1c6b84121093a8d9 authority=kernel-proved theorems=EccFormal.ApproxReplayBadEvents.replay_exact_of_no_bad_along,EccFormal.ApproxReplayBadEvents.final_mismatch_implies_bad_visited
// formal-input: formal/lean/EccFormal/LoanAwareHybridAdder.lean sha256=7aa55ec68bea0f56987dffd5baba336ce941e64b3442b9adb9cdc5c40e851439 authority=design-provenance theorems=EccFormal.LoanAwareHybridAdder.masked_add_refines_controlled_add,EccFormal.LoanAwareHybridAdder.loaded_loan_restores_clean
// formal-input: formal/lean/EccFormal/PrefixComparator.lean sha256=0711ec8db304a58b077eb5d519d8db94d14cb309502a6318ca129c36cb0be02e authority=design-provenance theorems=EccFormal.PrefixComparator.prefix_less_exact_off_bad_event
// authority-boundary: deterministic structural generation; theorem scope remains per formal-input
// DO NOT EDIT; regenerate from the reviewed profile.
use super::*;

#[derive(Clone, Copy)]
enum SignedOp {
    Add,
    Sub,
}

impl SignedOp {
    fn flipped(self) -> Self {
        match self {
            Self::Add => Self::Sub,
            Self::Sub => Self::Add,
        }
    }
}

fn apply_operand(b: &mut B, acc: &[QubitId], operand: &[QubitId], op: SignedOp, p: U256) {
    match op {
        SignedOp::Add => mod_add_qq_fast(b, acc, operand, p),
        SignedOp::Sub => mod_sub_qq_fast(b, acc, operand, p),
    }
}

// Apply value*2^shift where the represented integer is strictly below p.
// A 256-bit window is split at its top bit, so no modular primitive receives
// an unproved non-canonical operand.
fn apply_fitting_shifted(
    b: &mut B,
    acc: &[QubitId],
    value: &[QubitId],
    shift: usize,
    op: SignedOp,
    p: U256,
) {
    if value.is_empty() {
        return;
    }
    assert!(value.len() + shift <= 256);
    if value.len() + shift == 256 && value.len() > 1 {
        let split = value.len() - 1;
        apply_fitting_shifted(b, acc, &value[..split], shift, op, p);
        apply_fitting_shifted(b, acc, &value[split..], shift + split, op, p);
        return;
    }
    let low_padding = b.alloc_qubits(shift);
    let high_padding = b.alloc_qubits(256 - shift - value.len());
    let mut operand = Vec::with_capacity(256);
    operand.extend_from_slice(&low_padding);
    operand.extend_from_slice(value);
    operand.extend_from_slice(&high_padding);
    apply_operand(b, acc, &operand, op, p);
    b.free_vec(&high_padding);
    b.free_vec(&low_padding);
}

// F = 2^32 + 977 = 2^0 + 2^4 - 2^6 + 2^10 + 2^32.
const F_NAF: [(usize, bool); 5] = [(0, false), (4, false), (6, true), (10, false), (32, false)];

fn apply_narrow_times_f(b: &mut B, acc: &[QubitId], value: &[QubitId], op: SignedOp, p: U256) {
    assert!(value.len() + 32 <= 256);
    for (shift, negative) in F_NAF {
        let term_op = if negative { op.flipped() } else { op };
        apply_fitting_shifted(b, acc, value, shift, term_op, p);
    }
}

// Reduce one shifted exact product with 2^256 = F (mod p). The overflow
// tail is narrow for every reviewed call, so one fold is sufficient.
fn apply_shifted_product(
    b: &mut B,
    acc: &[QubitId],
    product: &[QubitId],
    shift: usize,
    op: SignedOp,
    p: U256,
) {
    assert!(shift < 256);
    let cutoff = 256 - shift;
    let low_len = product.len().min(cutoff);
    apply_fitting_shifted(b, acc, &product[..low_len], shift, op, p);
    if product.len() > cutoff {
        apply_narrow_times_f(b, acc, &product[cutoff..], op, p);
    }
}

// The reviewed caller supplies b^2 < p. Walk that canonical product through
// the NAF powers in place, then apply the exact inverse walk back to b^2.
fn apply_product_times_f(b: &mut B, acc: &[QubitId], product: &[QubitId], op: SignedOp, p: U256) {
    assert_eq!(product.len(), 256);
    apply_operand(b, acc, product, op, p);
    for _ in 0..4 {
        mod_double_inplace_fast(b, product, p);
    }
    apply_operand(b, acc, product, op, p);
    for _ in 0..2 {
        mod_double_inplace_fast(b, product, p);
    }
    apply_operand(b, acc, product, op.flipped(), p);
    for _ in 0..4 {
        mod_double_inplace_fast(b, product, p);
    }
    apply_operand(b, acc, product, op, p);
    for _ in 0..22 {
        mod_double_inplace_fast(b, product, p);
    }
    apply_operand(b, acc, product, op, p);
    for _ in 0..32 {
        mod_halve_inplace_fast(b, product, p);
    }
}

pub(super) fn squaring_sub_from_acc_half_products_exact(
    b: &mut B,
    acc: &[QubitId],
    x: &[QubitId],
    p: U256,
) {
    assert_eq!(acc.len(), 256);
    assert_eq!(x.len(), 256);
    let a = &x[..128];
    let high = &x[128..];

    let sum = b.alloc_qubits(129);
    karatsuba_half_sum_compute(b, a, high, &sum);

    let product = b.alloc_qubits(256);
    schoolbook_square_symmetric(b, a, &product);
    apply_shifted_product(b, acc, &product, 0, SignedOp::Sub, p);
    apply_shifted_product(b, acc, &product, 128, SignedOp::Add, p);
    schoolbook_square_symmetric_inverse(b, a, &product);
    b.free_vec(&product);

    let product = b.alloc_qubits(256);
    schoolbook_square_symmetric(b, high, &product);
    apply_shifted_product(b, acc, &product, 128, SignedOp::Add, p);
    apply_product_times_f(b, acc, &product, SignedOp::Sub, p);
    schoolbook_square_symmetric_inverse(b, high, &product);
    b.free_vec(&product);

    let product = b.alloc_qubits(258);
    schoolbook_square_symmetric(b, &sum, &product);
    apply_shifted_product(b, acc, &product, 128, SignedOp::Sub, p);
    schoolbook_square_symmetric_inverse(b, &sum, &product);
    b.free_vec(&product);

    karatsuba_half_sum_uncompute(b, a, high, &sum);
    b.free_vec(&sum);
}
