// @generated by tools/ecdlp_codegen.py
// generator-version: ecdlp-codegen/v1
// generator-sha256: 9f2e055ad2441049ef63a01ac34341c7fcc8880323d3734b573036cb5d6d8471
// profile-sha256: afc3be6a118b3dead47539821d6e0f4eb7186479b0ffdcead2c95eecc8e91790
// artifact: generated_exact_solinas.rs
// formal-input: formal/lean/EccFormal/PointAddAlgorithm.lean sha256=e83ac9d653eea9750badc997f47623f38b7713962a792c5a3cca052df6096184 authority=kernel-proved theorems=EccFormal.PointAddAlgorithm.parent_register_composition_refines_affine
// formal-input: formal/lean/EccFormal/BinaryGcdConvergence.lean sha256=628c7ba200df167c9707dfedcf381b9a344bd1b550f4157404dbf46ccda90712 authority=kernel-proved theorems=EccFormal.BinaryGcdConvergence.secp256k1_complete_fixed_511
// formal-input: formal/lean/EccFormal/BinaryGcdGarbageReplay.lean sha256=39b046f88cc76dc84a776c71a66a28b66d11989dbce6c3bb89565e3f4b027542 authority=kernel-proved theorems=EccFormal.BinaryGcdGarbageReplay.inverse_value_walk_restores_complete_trace,EccFormal.BinaryGcdGarbageReplay.coefficient_replay_complete_coprime_orientation,EccFormal.BinaryGcdGarbageReplay.coefficient_replay_complete_coprime_inverse_orientation
// formal-input: formal/lean/EccFormal/BinaryGcdInPlaceMultiplication.lean sha256=2ff4c7e2cb450e8a8c2b1fc668f966bc7a1747a533c5fbd23d3b24b4bc2b0395 authority=kernel-proved theorems=EccFormal.BinaryGcdInPlaceMultiplication.complete_in_place_multiply_relation
// formal-input: formal/lean/EccFormal/BinaryGcdPhysicalRelease.lean sha256=ebd123fb2916831caf2f5dd9a4ae3670071e4bc12c48bf629ecbc72c5bb46668 authority=kernel-proved theorems=EccFormal.BinaryGcdPhysicalRelease.secp256k1_uniform_high_wires_clear,EccFormal.BinaryGcdPhysicalRelease.fixed_replay_peak_with_seven_scratch
// formal-input: formal/lean/EccFormal/BinaryGcdUniformLedger.lean sha256=1032c4b9fd203bd502aa577468a06a2e80200a9a64ae682a90b134eeadfa1ae4 authority=kernel-proved theorems=EccFormal.BinaryGcdUniformLedger.secp256k1_uniform_component_widths,EccFormal.BinaryGcdUniformLedger.forward_persistent_cap
// formal-input: formal/lean/EccFormal/ApproxReplayBadEvents.lean sha256=064f5d305cf9bd94e6e2a56abbf997ad70c1b46bc3c8b68c1c6b84121093a8d9 authority=kernel-proved theorems=EccFormal.ApproxReplayBadEvents.replay_exact_of_no_bad_along,EccFormal.ApproxReplayBadEvents.final_mismatch_implies_bad_visited
// formal-input: formal/lean/EccFormal/LoanAwareHybridAdder.lean sha256=7aa55ec68bea0f56987dffd5baba336ce941e64b3442b9adb9cdc5c40e851439 authority=design-provenance theorems=EccFormal.LoanAwareHybridAdder.masked_add_refines_controlled_add,EccFormal.LoanAwareHybridAdder.loaded_loan_restores_clean
// formal-input: formal/lean/EccFormal/PrefixComparator.lean sha256=0711ec8db304a58b077eb5d519d8db94d14cb309502a6318ca129c36cb0be02e authority=design-provenance theorems=EccFormal.PrefixComparator.prefix_less_exact_off_bad_event
// authority-boundary: deterministic structural generation; theorem scope remains per formal-input
// DO NOT EDIT; regenerate from the reviewed profile.
use super::*;

const SPECIALIZED_SHIFT_BITS: usize = 0;
const DOUBLE_HALVE_WALK_BITS: usize = 22;

fn walk_forward(b: &mut B, value: &[QubitId], p: U256) {
    for _ in 0..DOUBLE_HALVE_WALK_BITS {
        mod_double_inplace_fast(b, value, p);
    }
}

fn walk_backward(b: &mut B, value: &[QubitId], p: U256) {
    for _ in 0..DOUBLE_HALVE_WALK_BITS {
        mod_halve_inplace_fast(b, value, p);
    }
}

pub(super) fn add_power32_from_power10(
    b: &mut B,
    acc: &[QubitId],
    value_at_power10: &[QubitId],
    p: U256,
) {
    walk_forward(b, value_at_power10, p);
    mod_add_qq(b, acc, value_at_power10, p);
    walk_backward(b, value_at_power10, p);
}

pub(super) fn sub_power32_from_power10(
    b: &mut B,
    acc: &[QubitId],
    value_at_power10: &[QubitId],
    p: U256,
) {
    walk_forward(b, value_at_power10, p);
    mod_sub_qq(b, acc, value_at_power10, p);
    walk_backward(b, value_at_power10, p);
}
