// @generated by tools/clean_point_add.py; DO NOT EDIT.
// rewrite-profile: clean-point-add-target-fanout-v1
// canonical-spec-sha256: 313a450c2bba6e2e17bebf967cdb62e317535322bf7dd18229d3e448aa1e0173
// The matcher is deliberately fail-closed: every reviewed source witness
// must still occur at its absolute parent-stream index before any rewrite runs.

use super::*;

const EXPECTED_INPUT_OPS: usize = 40922100;
const EXPECTED_OUTPUT_OPS: usize = 40922095;

#[derive(Clone, Copy)]
struct Witness {
    first: usize,
    control_low: u64,
    control_high: u64,
    temporary: u64,
    output: u64,
    condition: u64,
    condition_depth: usize,
}

const WITNESSES: [Witness; 5] = [
    Witness {
        first: 8440454,
        control_low: 766,
        control_high: 1025,
        temporary: 767,
        output: 2708,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 11789045,
        control_low: 510,
        control_high: 771,
        temporary: 511,
        output: 2769,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 20728552,
        control_low: 254,
        control_high: 1028,
        temporary: 255,
        output: 1289,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 21958193,
        control_low: 510,
        control_high: 772,
        temporary: 511,
        output: 1977,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 32548557,
        control_low: 766,
        control_high: 768,
        temporary: 767,
        output: 2636,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
];

macro_rules! assert_field {
    ($actual:expr, $expected:expr, $label:literal, $witness:expr) => {
        assert_eq!($actual, $expected, "{} drift at {}", $label, $witness.first);
    };
}

fn assert_witness(ops: &[Op], witness: Witness, condition_depth: usize) {
    let first = ops[witness.first];
    let middle = ops[witness.first + 1];
    let last = ops[witness.first + 2];
    let mut first_controls = [first.q_control1.0, first.q_control2.0];
    let mut last_controls = [last.q_control1.0, last.q_control2.0];
    first_controls.sort_unstable();
    last_controls.sort_unstable();
    let expected_controls = [witness.control_low, witness.control_high];
    assert_field!(condition_depth, witness.condition_depth, "depth", witness);
    assert_field!(first.kind, OperationType::CCX, "first gate", witness);
    assert_field!(middle.kind, OperationType::CX, "middle gate", witness);
    assert_field!(last.kind, OperationType::CCX, "last gate", witness);
    assert_field!(first_controls, expected_controls, "first controls", witness);
    assert_field!(last_controls, expected_controls, "last controls", witness);
    assert_field!(first.q_target.0, witness.temporary, "first target", witness);
    assert_field!(last.q_target.0, witness.temporary, "last target", witness);
    let fanout_control = middle.q_control1.0;
    assert_field!(fanout_control, witness.temporary, "fanout control", witness);
    assert_field!(middle.q_control2.0, u64::MAX, "second CX control", witness);
    assert_field!(middle.q_target.0, witness.output, "fanout target", witness);
    for op in [first, middle, last] {
        assert_field!(op.c_target.0, u64::MAX, "classical target", witness);
        let inline_condition = op.c_condition.0;
        assert_field!(inline_condition, witness.condition, "condition", witness);
        assert_field!(op.r_target.0, u64::MAX, "register target", witness);
    }
}

pub(super) fn apply_exact_rewrites(ops: Vec<Op>) -> Vec<Op> {
    assert_eq!(ops.len(), EXPECTED_INPUT_OPS);
    let mut output = Vec::with_capacity(EXPECTED_OUTPUT_OPS);
    let mut source_index = 0usize;
    let mut witness_index = 0usize;
    let mut condition_depth = 0usize;
    while source_index < ops.len() {
        let is_witness =
            witness_index < WITNESSES.len() && source_index == WITNESSES[witness_index].first;
        if is_witness {
            let witness = WITNESSES[witness_index];
            assert_witness(&ops, witness, condition_depth);
            let middle = ops[source_index + 1];
            let mut redirected = ops[source_index];
            redirected.q_target = middle.q_target;
            redirected.validate();
            output.push(middle);
            output.push(redirected);
            source_index += 3;
            witness_index += 1;
            continue;
        }
        let op = ops[source_index];
        match op.kind {
            OperationType::PushCondition => condition_depth += 1,
            OperationType::PopCondition => {
                assert!(condition_depth > 0, "underflow at {}", source_index);
                condition_depth -= 1;
            }
            _ => {}
        }
        output.push(op);
        source_index += 1;
    }
    assert_eq!(witness_index, WITNESSES.len());
    assert_eq!(condition_depth, 0);
    assert_eq!(output.len(), EXPECTED_OUTPUT_OPS);
    output
}
