// @generated by tools/clean_point_add.py; DO NOT EDIT.
// algorithm: clean-point-add-secp256k1-affine-v1
// canonical-spec-sha256: b5b87102377f946e777ba3f9fcc621da43911fb6c73201c76b604ff40e0ca3d6
// The Lean/Z3 contracts prove value-level equations only; source lowering and
// emitted-stream equivalence remain separate workflow gates.

use super::*;

pub(super) fn emit_point_add(
    b: &mut B,
    tx: &[QubitId],
    ty: &[QubitId],
    ox: &[BitId],
    oy: &[BitId],
) {
    let p = SECP256K1_P;
    let pair1_iters = 2 * N - 1;
    let pair2_iters = 2 * N - 1;
    b.set_phase("coordinate_differences");
    mod_sub_qb(b, tx, ox, p);
    mod_sub_qb(b, ty, oy, p);
    let lam = b.alloc_qubits(N);
    b.set_phase("pair1_kaliski_forward");
    with_kal_inv_raw(b, tx, p, pair1_iters, |b, inv_raw| {
        b.set_phase("pair1_mul1");
        mod_mul_write_into_zero_acc_schoolbook(b, &lam, ty, inv_raw, p);
        b.set_phase("pair1_halve");
        for _ in 0..pair1_iters {
            mod_halve_inplace_fast(b, &lam, p);
        }
        b.set_phase("pair1_mul2");
        mod_mul_add_into_acc_schoolbook(b, ty, &lam, tx, p);
        b.set_phase("pair1_kaliski_backward");
    });
    b.set_phase("x_coordinate_and_pair2_denominator");
    mod_mul_sub_qq(b, tx, &lam, &lam, p);
    mod_add_double_qb(b, tx, ox, p);
    mod_add_qb(b, tx, ox, p);
    mod_neg_inplace_fast(b, tx, p);
    b.set_phase("mul3_between_pair");
    mod_mul_write_into_zero_acc_karatsuba2(b, ty, &lam, tx, p);
    b.set_phase("pair2_kaliski_forward");
    with_kal_inv_raw(b, tx, p, pair2_iters, |b, inv_raw| {
        b.set_phase("pair2_double");
        for _ in 0..pair2_iters {
            mod_double_inplace_fast(b, &lam, p);
        }
        b.set_phase("pair2_mul");
        mod_mul_add_into_acc_schoolbook(b, &lam, inv_raw, ty, p);
        b.set_phase("pair2_cleanup");
        mod_sub_qb(b, ty, oy, p);
        b.set_phase("pair2_kaliski_backward");
    });
    b.set_phase("final_coordinate_restore");
    mod_add_qb(b, tx, ox, p);
    b.free_vec(&lam);
}
