// @generated by tools/clean_point_add.py; DO NOT EDIT.
// exact-solinas-profile: clean-point-add-exact-solinas-walk-v1
// canonical-spec-sha256: e69ede61fda471df47a101065aa22f184306b2886fb391b445b0815ba4f94def
// The value theorem covers the double/halve walk only. Primitive refinement,
// measurement phase, allocation, and whole-stream correctness remain separate gates.

use super::*;

const SPECIALIZED_SHIFT_BITS: usize = 0;
const DOUBLE_HALVE_WALK_BITS: usize = 22;

fn walk_forward(b: &mut B, value: &[QubitId], p: U256) {
    for _ in 0..DOUBLE_HALVE_WALK_BITS {
        mod_double_inplace_fast(b, value, p);
    }
}

fn walk_backward(b: &mut B, value: &[QubitId], p: U256) {
    for _ in 0..DOUBLE_HALVE_WALK_BITS {
        mod_halve_inplace_fast(b, value, p);
    }
}

pub(super) fn add_power32_from_power10(
    b: &mut B,
    acc: &[QubitId],
    value_at_power10: &[QubitId],
    p: U256,
) {
    walk_forward(b, value_at_power10, p);
    mod_add_qq(b, acc, value_at_power10, p);
    walk_backward(b, value_at_power10, p);
}

pub(super) fn sub_power32_from_power10(
    b: &mut B,
    acc: &[QubitId],
    value_at_power10: &[QubitId],
    p: U256,
) {
    walk_forward(b, value_at_power10, p);
    mod_sub_qq(b, acc, value_at_power10, p);
    walk_backward(b, value_at_power10, p);
}
