// @generated by tools/clean_point_add.py; DO NOT EDIT.
// epoch-fanout-profile: clean-point-add-epoch-target-fanout-v1
// canonical-spec-sha256: c254124b30df9ce66b2f5ee07b81834ed1d5d222e7deac5dca9e513cb109b8f3
// bound-scan-sha256: 3e40d2ed64f13f82f851f4a6a68e5ff3a6a3298f72dd419895745c46dc8fdcfe
// Each source-bound window is checked again against the commuting-context ledger.

use super::*;

const EXPECTED_INPUT_OPS: usize = 41431586;
const EXPECTED_OUTPUT_OPS: usize = 41431550;

#[derive(Clone, Copy)]
struct Witness {
    first: usize,
    blocker: usize,
    second: usize,
    control_low: u64,
    control_high: u64,
    temporary: u64,
    output: u64,
    condition: u64,
    condition_depth: usize,
}

const WITNESSES: [Witness; 36] = [
    Witness {
        first: 8315517,
        blocker: 8315519,
        second: 8315520,
        control_low: 1026,
        control_high: 2437,
        temporary: 2382,
        output: 1025,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 8477763,
        blocker: 8477764,
        second: 8477766,
        control_low: 767,
        control_high: 1026,
        temporary: 1025,
        output: 1024,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 8479309,
        blocker: 8479310,
        second: 8479312,
        control_low: 767,
        control_high: 2469,
        temporary: 2317,
        output: 1024,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 8481121,
        blocker: 8481123,
        second: 8481124,
        control_low: 767,
        control_high: 2444,
        temporary: 2382,
        output: 1024,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 8483182,
        blocker: 8483183,
        second: 8483184,
        control_low: 766,
        control_high: 1025,
        temporary: 767,
        output: 2306,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 8586903,
        blocker: 8586904,
        second: 8586906,
        control_low: 1026,
        control_high: 2437,
        temporary: 2444,
        output: 1025,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 11747233,
        blocker: 11747235,
        second: 11747236,
        control_low: 772,
        control_high: 2437,
        temporary: 2444,
        output: 771,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 11911786,
        blocker: 11911787,
        second: 11911789,
        control_low: 511,
        control_high: 772,
        temporary: 771,
        output: 770,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 11913332,
        blocker: 11913333,
        second: 11913335,
        control_low: 511,
        control_high: 2305,
        temporary: 2317,
        output: 770,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 11915144,
        blocker: 11915146,
        second: 11915147,
        control_low: 511,
        control_high: 2514,
        temporary: 2324,
        output: 770,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 11917205,
        blocker: 11917206,
        second: 11917207,
        control_low: 510,
        control_high: 771,
        temporary: 511,
        output: 2469,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 12020926,
        blocker: 12020927,
        second: 12020929,
        control_low: 772,
        control_high: 2521,
        temporary: 2514,
        output: 771,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 21677938,
        blocker: 21677940,
        second: 21677941,
        control_low: 1123,
        control_high: 1768,
        temporary: 1769,
        output: 1026,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 21729730,
        blocker: 21729732,
        second: 21729733,
        control_low: 899,
        control_high: 1768,
        temporary: 1769,
        output: 898,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 21784510,
        blocker: 21784512,
        second: 21784513,
        control_low: 1397,
        control_high: 2102,
        temporary: 2101,
        output: 1150,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 21842430,
        blocker: 21842432,
        second: 21842433,
        control_low: 897,
        control_high: 1765,
        temporary: 1766,
        output: 896,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 21894222,
        blocker: 21894224,
        second: 21894225,
        control_low: 893,
        control_high: 1765,
        temporary: 1766,
        output: 1156,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 21949002,
        blocker: 21949004,
        second: 21949005,
        control_low: 1702,
        control_high: 2297,
        temporary: 1701,
        output: 1500,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 22161846,
        blocker: 22161848,
        second: 22161849,
        control_low: 1361,
        control_high: 1910,
        temporary: 1909,
        output: 1363,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 22334124,
        blocker: 22334125,
        second: 22334127,
        control_low: 511,
        control_high: 893,
        temporary: 1156,
        output: 1765,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 22335670,
        blocker: 22335671,
        second: 22335673,
        control_low: 511,
        control_high: 2024,
        temporary: 2023,
        output: 1765,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 22337482,
        blocker: 22337484,
        second: 22337485,
        control_low: 511,
        control_high: 1761,
        temporary: 1760,
        output: 1765,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 22339543,
        blocker: 22339544,
        second: 22339545,
        control_low: 510,
        control_high: 1156,
        temporary: 511,
        output: 1762,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 22453165,
        blocker: 22453166,
        second: 22453168,
        control_low: 1361,
        control_high: 2120,
        temporary: 2121,
        output: 1363,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 22666201,
        blocker: 22666202,
        second: 22666204,
        control_low: 1942,
        control_high: 2297,
        temporary: 1943,
        output: 1500,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 22721112,
        blocker: 22721113,
        second: 22721115,
        control_low: 893,
        control_high: 1765,
        temporary: 1766,
        output: 1156,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 22772904,
        blocker: 22772905,
        second: 22772907,
        control_low: 897,
        control_high: 1765,
        temporary: 1766,
        output: 896,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 22830693,
        blocker: 22830694,
        second: 22830696,
        control_low: 1397,
        control_high: 1928,
        temporary: 1929,
        output: 1150,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 22885604,
        blocker: 22885605,
        second: 22885607,
        control_low: 899,
        control_high: 2020,
        temporary: 1769,
        output: 898,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 22937396,
        blocker: 22937397,
        second: 22937399,
        control_low: 1123,
        control_high: 2020,
        temporary: 1769,
        output: 1026,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 32845367,
        blocker: 32845369,
        second: 32845370,
        control_low: 1161,
        control_high: 2521,
        temporary: 2514,
        output: 1160,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 33009920,
        blocker: 33009921,
        second: 33009923,
        control_low: 767,
        control_high: 1161,
        temporary: 1160,
        output: 1159,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 33011466,
        blocker: 33011467,
        second: 33011469,
        control_low: 767,
        control_high: 2306,
        temporary: 2317,
        output: 1159,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 33013278,
        blocker: 33013280,
        second: 33013281,
        control_low: 767,
        control_high: 2382,
        temporary: 2444,
        output: 1159,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 33015339,
        blocker: 33015340,
        second: 33015341,
        control_low: 766,
        control_high: 1160,
        temporary: 767,
        output: 2305,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
    Witness {
        first: 33119060,
        blocker: 33119061,
        second: 33119063,
        control_low: 1161,
        control_high: 2437,
        temporary: 2382,
        output: 1160,
        condition: 18446744073709551615,
        condition_depth: 0,
    },
];

fn assert_endpoint(op: Op, witness: Witness) {
    let mut controls = [op.q_control1.0, op.q_control2.0];
    controls.sort_unstable();
    assert_eq!(op.kind, OperationType::CCX);
    assert_eq!(controls, [witness.control_low, witness.control_high]);
    assert_eq!(op.q_target.0, witness.temporary);
    assert_eq!(op.c_target.0, u64::MAX);
    assert_eq!(op.c_condition.0, u64::MAX);
    assert_eq!(op.r_target.0, u64::MAX);
}

fn assert_blocker(op: Op, witness: Witness) {
    assert_eq!(op.kind, OperationType::CX);
    assert_eq!(op.q_control1.0, witness.temporary);
    assert_eq!(op.q_control2.0, u64::MAX);
    assert_eq!(op.q_target.0, witness.output);
    assert_eq!(op.c_target.0, u64::MAX);
    assert_eq!(op.c_condition.0, witness.condition);
    assert_eq!(op.r_target.0, u64::MAX);
}

fn commutes_with_endpoint(op: Op, witness: Witness) -> bool {
    let a = witness.control_low;
    let control_b = witness.control_high;
    let temporary = witness.temporary;
    match op.kind {
        OperationType::X => op.q_target.0 != a && op.q_target.0 != control_b,
        OperationType::CX => {
            op.q_target.0 != a && op.q_target.0 != control_b && op.q_control1.0 != temporary
        }
        OperationType::CCX => {
            op.q_target.0 != a
                && op.q_target.0 != control_b
                && op.q_control1.0 != temporary
                && op.q_control2.0 != temporary
        }
        OperationType::Z => op.q_target.0 != temporary,
        OperationType::CZ => op.q_control1.0 != temporary && op.q_target.0 != temporary,
        OperationType::CCZ => {
            op.q_control1.0 != temporary
                && op.q_control2.0 != temporary
                && op.q_target.0 != temporary
        }
        OperationType::Swap => {
            let mut pair = [op.q_control1.0, op.q_target.0];
            pair.sort_unstable();
            let touches =
                pair.contains(&a) || pair.contains(&control_b) || pair.contains(&temporary);
            !touches || pair == [a, control_b]
        }
        OperationType::R | OperationType::Hmr => {
            ![a, control_b, temporary].contains(&op.q_target.0)
        }
        OperationType::PushCondition | OperationType::PopCondition => false,
        OperationType::Neg
        | OperationType::Register
        | OperationType::AppendToRegister
        | OperationType::BitInvert
        | OperationType::BitStore0
        | OperationType::BitStore1
        | OperationType::DebugPrint => true,
    }
}

fn replacement(blocker: Op, witness: Witness) -> Op {
    let mut op = Op::empty();
    op.kind = OperationType::CCX;
    op.q_control2 = QubitId(witness.control_low);
    op.q_control1 = QubitId(witness.control_high);
    op.q_target = QubitId(witness.output);
    op.c_condition = blocker.c_condition;
    op.validate();
    op
}

pub(super) fn apply_epoch_fanout(ops: Vec<Op>) -> Vec<Op> {
    assert_eq!(ops.len(), EXPECTED_INPUT_OPS);
    let mut output = Vec::with_capacity(EXPECTED_OUTPUT_OPS);
    let mut source_index = 0usize;
    let mut witness_index = 0usize;
    let mut condition_depth = 0usize;
    while source_index < ops.len() {
        if witness_index < WITNESSES.len() && source_index == WITNESSES[witness_index].first {
            let witness = WITNESSES[witness_index];
            assert_eq!(condition_depth, witness.condition_depth);
            assert_endpoint(ops[witness.first], witness);
            assert_blocker(ops[witness.blocker], witness);
            assert_endpoint(ops[witness.second], witness);
            for index in witness.first + 1..witness.second {
                let op = ops[index];
                if index != witness.blocker {
                    assert!(
                        commutes_with_endpoint(op, witness),
                        "ledger drift at {index}"
                    );
                }
                output.push(op);
                if index == witness.blocker {
                    output.push(replacement(op, witness));
                }
            }
            source_index = witness.second + 1;
            witness_index += 1;
            continue;
        }
        let op = ops[source_index];
        match op.kind {
            OperationType::PushCondition => condition_depth += 1,
            OperationType::PopCondition => {
                assert!(condition_depth > 0, "condition underflow at {source_index}");
                condition_depth -= 1;
            }
            _ => {}
        }
        output.push(op);
        source_index += 1;
    }
    assert_eq!(witness_index, WITNESSES.len());
    assert_eq!(condition_depth, 0);
    assert_eq!(output.len(), EXPECTED_OUTPUT_OPS);
    output
}
