// @generated by tools/clean_point_add.py; DO NOT EDIT.
// exact-square-profile: clean-point-add-half-product-square-v1
// canonical-spec-sha256: 25f1a714966809687d8818fd4da6b30751b586c13a827db159e09298faffd228
// Lean proves the five-term value identity. This lowering deliberately uses
// full modular primitives and does not import Teddy's truncated guards or comparator.

use super::*;

#[derive(Clone, Copy)]
enum SignedOp {
    Add,
    Sub,
}

impl SignedOp {
    fn flipped(self) -> Self {
        match self {
            Self::Add => Self::Sub,
            Self::Sub => Self::Add,
        }
    }
}

fn apply_operand(b: &mut B, acc: &[QubitId], operand: &[QubitId], op: SignedOp, p: U256) {
    match op {
        SignedOp::Add => mod_add_qq_fast(b, acc, operand, p),
        SignedOp::Sub => mod_sub_qq_fast(b, acc, operand, p),
    }
}

// Apply value*2^shift where the represented integer is strictly below p.
// A 256-bit window is split at its top bit, so no modular primitive receives
// an unproved non-canonical operand.
fn apply_fitting_shifted(
    b: &mut B,
    acc: &[QubitId],
    value: &[QubitId],
    shift: usize,
    op: SignedOp,
    p: U256,
) {
    if value.is_empty() {
        return;
    }
    assert!(value.len() + shift <= 256);
    if value.len() + shift == 256 && value.len() > 1 {
        let split = value.len() - 1;
        apply_fitting_shifted(b, acc, &value[..split], shift, op, p);
        apply_fitting_shifted(b, acc, &value[split..], shift + split, op, p);
        return;
    }
    let low_padding = b.alloc_qubits(shift);
    let high_padding = b.alloc_qubits(256 - shift - value.len());
    let mut operand = Vec::with_capacity(256);
    operand.extend_from_slice(&low_padding);
    operand.extend_from_slice(value);
    operand.extend_from_slice(&high_padding);
    apply_operand(b, acc, &operand, op, p);
    b.free_vec(&high_padding);
    b.free_vec(&low_padding);
}

// F = 2^32 + 977 = 2^0 + 2^4 - 2^6 + 2^10 + 2^32.
const F_NAF: [(usize, bool); 5] = [(0, false), (4, false), (6, true), (10, false), (32, false)];

fn apply_narrow_times_f(b: &mut B, acc: &[QubitId], value: &[QubitId], op: SignedOp, p: U256) {
    assert!(value.len() + 32 <= 256);
    for (shift, negative) in F_NAF {
        let term_op = if negative { op.flipped() } else { op };
        apply_fitting_shifted(b, acc, value, shift, term_op, p);
    }
}

// Reduce one shifted exact product with 2^256 = F (mod p). The overflow
// tail is narrow for every reviewed call, so one fold is sufficient.
fn apply_shifted_product(
    b: &mut B,
    acc: &[QubitId],
    product: &[QubitId],
    shift: usize,
    op: SignedOp,
    p: U256,
) {
    assert!(shift < 256);
    let cutoff = 256 - shift;
    let low_len = product.len().min(cutoff);
    apply_fitting_shifted(b, acc, &product[..low_len], shift, op, p);
    if product.len() > cutoff {
        apply_narrow_times_f(b, acc, &product[cutoff..], op, p);
    }
}

// The reviewed caller supplies b^2 < p. Walk that canonical product through
// the NAF powers in place, then apply the exact inverse walk back to b^2.
fn apply_product_times_f(b: &mut B, acc: &[QubitId], product: &[QubitId], op: SignedOp, p: U256) {
    assert_eq!(product.len(), 256);
    apply_operand(b, acc, product, op, p);
    for _ in 0..4 {
        mod_double_inplace_fast(b, product, p);
    }
    apply_operand(b, acc, product, op, p);
    for _ in 0..2 {
        mod_double_inplace_fast(b, product, p);
    }
    apply_operand(b, acc, product, op.flipped(), p);
    for _ in 0..4 {
        mod_double_inplace_fast(b, product, p);
    }
    apply_operand(b, acc, product, op, p);
    for _ in 0..22 {
        mod_double_inplace_fast(b, product, p);
    }
    apply_operand(b, acc, product, op, p);
    for _ in 0..32 {
        mod_halve_inplace_fast(b, product, p);
    }
}

pub(super) fn squaring_sub_from_acc_half_products_exact(
    b: &mut B,
    acc: &[QubitId],
    x: &[QubitId],
    p: U256,
) {
    assert_eq!(acc.len(), 256);
    assert_eq!(x.len(), 256);
    let a = &x[..128];
    let high = &x[128..];

    let sum = b.alloc_qubits(129);
    karatsuba_half_sum_compute(b, a, high, &sum);

    let product = b.alloc_qubits(256);
    schoolbook_square_symmetric(b, a, &product);
    apply_shifted_product(b, acc, &product, 0, SignedOp::Sub, p);
    apply_shifted_product(b, acc, &product, 128, SignedOp::Add, p);
    schoolbook_square_symmetric_inverse(b, a, &product);
    b.free_vec(&product);

    let product = b.alloc_qubits(256);
    schoolbook_square_symmetric(b, high, &product);
    apply_shifted_product(b, acc, &product, 128, SignedOp::Add, p);
    apply_product_times_f(b, acc, &product, SignedOp::Sub, p);
    schoolbook_square_symmetric_inverse(b, high, &product);
    b.free_vec(&product);

    let product = b.alloc_qubits(258);
    schoolbook_square_symmetric(b, &sum, &product);
    apply_shifted_product(b, acc, &product, 128, SignedOp::Sub, p);
    schoolbook_square_symmetric_inverse(b, &sum, &product);
    b.free_vec(&product);

    karatsuba_half_sum_uncompute(b, a, high, &sum);
    b.free_vec(&sum);
}
