// @generated by tools/ecdlp_codegen.py
// generator-version: ecdlp-codegen/v1
// generator-sha256: 9f2e055ad2441049ef63a01ac34341c7fcc8880323d3734b573036cb5d6d8471
// profile-sha256: afc3be6a118b3dead47539821d6e0f4eb7186479b0ffdcead2c95eecc8e91790
// artifact: generated_point_add.rs
// formal-input: formal/lean/EccFormal/PointAddAlgorithm.lean sha256=e83ac9d653eea9750badc997f47623f38b7713962a792c5a3cca052df6096184 authority=kernel-proved theorems=EccFormal.PointAddAlgorithm.parent_register_composition_refines_affine
// formal-input: formal/lean/EccFormal/BinaryGcdConvergence.lean sha256=628c7ba200df167c9707dfedcf381b9a344bd1b550f4157404dbf46ccda90712 authority=kernel-proved theorems=EccFormal.BinaryGcdConvergence.secp256k1_complete_fixed_511
// formal-input: formal/lean/EccFormal/BinaryGcdGarbageReplay.lean sha256=39b046f88cc76dc84a776c71a66a28b66d11989dbce6c3bb89565e3f4b027542 authority=kernel-proved theorems=EccFormal.BinaryGcdGarbageReplay.inverse_value_walk_restores_complete_trace,EccFormal.BinaryGcdGarbageReplay.coefficient_replay_complete_coprime_orientation,EccFormal.BinaryGcdGarbageReplay.coefficient_replay_complete_coprime_inverse_orientation
// formal-input: formal/lean/EccFormal/BinaryGcdInPlaceMultiplication.lean sha256=2ff4c7e2cb450e8a8c2b1fc668f966bc7a1747a533c5fbd23d3b24b4bc2b0395 authority=kernel-proved theorems=EccFormal.BinaryGcdInPlaceMultiplication.complete_in_place_multiply_relation
// formal-input: formal/lean/EccFormal/BinaryGcdPhysicalRelease.lean sha256=ebd123fb2916831caf2f5dd9a4ae3670071e4bc12c48bf629ecbc72c5bb46668 authority=kernel-proved theorems=EccFormal.BinaryGcdPhysicalRelease.secp256k1_uniform_high_wires_clear,EccFormal.BinaryGcdPhysicalRelease.fixed_replay_peak_with_seven_scratch
// formal-input: formal/lean/EccFormal/BinaryGcdUniformLedger.lean sha256=1032c4b9fd203bd502aa577468a06a2e80200a9a64ae682a90b134eeadfa1ae4 authority=kernel-proved theorems=EccFormal.BinaryGcdUniformLedger.secp256k1_uniform_component_widths,EccFormal.BinaryGcdUniformLedger.forward_persistent_cap
// formal-input: formal/lean/EccFormal/ApproxReplayBadEvents.lean sha256=064f5d305cf9bd94e6e2a56abbf997ad70c1b46bc3c8b68c1c6b84121093a8d9 authority=kernel-proved theorems=EccFormal.ApproxReplayBadEvents.replay_exact_of_no_bad_along,EccFormal.ApproxReplayBadEvents.final_mismatch_implies_bad_visited
// formal-input: formal/lean/EccFormal/LoanAwareHybridAdder.lean sha256=7aa55ec68bea0f56987dffd5baba336ce941e64b3442b9adb9cdc5c40e851439 authority=design-provenance theorems=EccFormal.LoanAwareHybridAdder.masked_add_refines_controlled_add,EccFormal.LoanAwareHybridAdder.loaded_loan_restores_clean
// formal-input: formal/lean/EccFormal/PrefixComparator.lean sha256=0711ec8db304a58b077eb5d519d8db94d14cb309502a6318ca129c36cb0be02e authority=design-provenance theorems=EccFormal.PrefixComparator.prefix_less_exact_off_bad_event
// authority-boundary: deterministic structural generation; theorem scope remains per formal-input
// DO NOT EDIT; regenerate from the reviewed profile.
use super::*;

pub(super) fn emit_point_add(
    b: &mut B,
    tx: &[QubitId],
    ty: &[QubitId],
    ox: &[BitId],
    oy: &[BitId],
) {
    // Two-block affine schedule. Besides the harness condition dx != 0,
    // the forward block assumes Rx-Qx != 0: the named event P = -2Q.
    let p = SECP256K1_P;
    b.set_phase("coordinate_differences");
    mod_sub_qb(b, tx, ox, p);
    mod_sub_qb(b, ty, oy, p);
    b.set_phase("pair1_binary_gcd_inverse");
    binary_gcd_in_place_inactive::emit_inactive_binary_gcd_inverse_in_place(b, tx, ty)
        .expect("frozen binary-GCD inverse stream must bind to the affine words");
    b.set_phase("canonical_slope_sign");
    mod_neg_inplace_canonical_fast(b, ty, p);
    b.set_phase("x_coordinate_and_pair2_denominator");
    mod_mul_sub_qq(b, tx, ty, ty, p);
    mod_add_double_qb(b, tx, ox, p);
    mod_add_qb(b, tx, ox, p);
    mod_neg_inplace_fast(b, tx, p);
    b.set_phase("pair2_binary_gcd_forward");
    binary_gcd_in_place_inactive::emit_inactive_binary_gcd_in_place(b, tx, ty)
        .expect("frozen binary-GCD forward stream must bind to the affine words");
    b.set_phase("final_coordinate_restore");
    mod_sub_qb(b, ty, oy, p);
    mod_add_qb(b, tx, ox, p);
}
